/**
 * Producer↔parser contract for `[browser-watch]` follow-up wakes.
 *
 * Every fixture is generated by the real runtime formatter
 * (formatBrowserWatchMessage) and fed to the UI parser (parseBrowserWatchSignal)
 * directly, so grammar drift between producer and parser fails here instead of
 * surfacing as mis-rendered user bubbles. Lives beside browser-watch-e2e.test.ts
 * because the ui package's tsc build cannot import .ts runtime paths
 * (TS5097); this app package builds via electron-vite, which type-strips.
 */
import { describe, expect, it } from 'vitest'
import { formatBrowserWatchMessage, type BrowserWatchTriggerReason } from '../../../../packs/agent-orchestration/subagent/browser-watch-delivery.ts'
import { parseBrowserWatchSignal } from '../../../../packages/ui/src/subagent-signal.ts'

describe('parseBrowserWatchSignal accepts real formatBrowserWatchMessage output', () => {
  it('parses the bare timeout layout with the fixed trailer', () => {
    const signal = parseBrowserWatchSignal(formatBrowserWatchMessage({ watchId: 'bw-2', reason: 'timeout', waitedMs: 61_000 }))!
    expect(signal).toMatchObject({ kind: 'browser-watch', tone: 'warning', summary: '等待超时 · bw-2' })
    expect(signal.fields.waitedMs).toBe('61000')
    expect(signal.detail).toContain('Use browser observe to inspect the current page.')
    expect(signal.detail).toContain('Do not treat this message as a new user request.')
  })

  it('parses the full layout with url, title, summary line and trailer', () => {
    const signal = parseBrowserWatchSignal(formatBrowserWatchMessage({
      watchId: 'bw-17', reason: 'matched', waitedMs: 4_200,
      url: 'https://example.com/ready', title: 'Example Ready',
      summary: '页面出现 .ready 元素',
    }))!
    expect(signal).toMatchObject({ kind: 'browser-watch', tone: 'success' })
    expect(signal.fields.url).toBe('https://example.com/ready')
    expect(signal.fields.title).toBe('Example Ready')
    expect(signal.summary).toBe('条件命中 · Example Ready')
    expect(signal.detail).toContain('页面出现 .ready 元素')
  })

  it('keeps a spaced url with field-lookalike text intact, with and without a title', () => {
    // oneLine() only collapses whitespace: a url may contain spaces AND
    // ` reason=` / ` waitedMs=` fragments. The parser must not truncate it.
    const noTitle = parseBrowserWatchSignal(formatBrowserWatchMessage({
      watchId: 'bw-11', reason: 'matched', waitedMs: 4_200,
      url: 'https://example.com/x reason=foo waitedMs=9',
    }))!
    expect(noTitle.fields.url).toBe('https://example.com/x reason=foo waitedMs=9')
    expect(noTitle.summary).toBe('条件命中 · https://example.com/x reason=foo waitedMs=9')
    expect(noTitle.fields.waitedMs).toBe('4200')

    // Canonical last-trailer split: the producer appends ` title=` after the
    // url, so the LAST ` title=` separates them and both values survive.
    const withTitle = parseBrowserWatchSignal(formatBrowserWatchMessage({
      watchId: 'bw-12', reason: 'matched', waitedMs: 4_200,
      url: 'https://example.com/x reason=foo', title: 'Example Ready',
    }))!
    expect(withTitle.fields.url).toBe('https://example.com/x reason=foo')
    expect(withTitle.fields.title).toBe('Example Ready')
    expect(withTitle.summary).toBe('条件命中 · Example Ready')
  })

  it('keeps a title containing field-lookalike text intact (title-only layout)', () => {
    const signal = parseBrowserWatchSignal(formatBrowserWatchMessage({
      watchId: 'bw-13', reason: 'matched', waitedMs: 10,
      title: '出现 reason=完成 waitedMs=提示',
    }))!
    expect(signal.fields.title).toBe('出现 reason=完成 waitedMs=提示')
    expect(signal.summary).toBe('条件命中 · 出现 reason=完成 waitedMs=提示')
  })

  it('recovers producer inputs for the documented url ` title=` ambiguity via last-trailer', () => {
    // The producer format has no escaping, so a url ending in ` title=Evil`
    // with a real title is inherently ambiguous. Last-trailer is the
    // conservative choice: the embedded fragment stays part of the url and the
    // appended tail is the title — exactly the producer's inputs.
    const signal = parseBrowserWatchSignal(formatBrowserWatchMessage({
      watchId: 'bw-14', reason: 'disposed', waitedMs: 8_000,
      url: 'https://x/p title=Evil', title: 'Real',
    }))!
    expect(signal.fields.url).toBe('https://x/p title=Evil')
    expect(signal.fields.title).toBe('Real')
  })

  it('stays neutral for a future reason value a newer runtime may emit', () => {
    // The producer type widens independently of the UI; the parser must
    // already accept any structurally valid reason. The cast simulates that
    // forward-compat scenario; it does not alter the formatter under test.
    const reason = 'expired' as BrowserWatchTriggerReason
    const signal = parseBrowserWatchSignal(formatBrowserWatchMessage({ watchId: 'bw-9', reason, waitedMs: 10 }))!
    expect(signal).toMatchObject({ kind: 'browser-watch', tone: 'neutral', summary: '浏览器监听通知 · expired' })
  })

  it('parses a wake re-wrapped by the durable delivery layer', () => {
    const base = formatBrowserWatchMessage({ watchId: 'bw-8', reason: 'timeout', waitedMs: 65_000, url: 'https://example.com/pending' })
    const wrapped = `(re-delivery #2: Pi did not confirm the prior follow-up; obligationId=o1; treat it as the same event.)\n${base}`
    const signal = parseBrowserWatchSignal(wrapped)!
    expect(signal).toMatchObject({ kind: 'browser-watch', delivery: 'retry' })
    expect(signal.fields.url).toBe('https://example.com/pending')
    expect(signal.detail).toContain('(re-delivery #2:')
  })
})
