/**
 * The COC-shaped context fold (contract §19.2).
 *
 * Pi's default compaction asks a model to summarise whatever it is about to drop. At this table
 * that is both expensive and wrong: most of what fills a long session is regenerated every single
 * turn (the capsule) or is machine-only (the mechanics projection, the tool round trips whose
 * receipts live in the kernel and come back through `recall`). What must survive is the transcript
 * — what the player said and what the Keeper delivered — and the last two turns whole.
 *
 * Pi's compaction hook takes a cut point plus one summary string: everything before
 * `firstKeptEntryId` is replaced by `summary`, everything from it on is kept verbatim
 * (`buildContextEntries` in the host's session manager). So the fold does two things: it picks the
 * cut at the start of the second-to-last turn, and it renders the summary itself — deterministically,
 * from the entries being dropped, with no model call at all.
 *
 * **The rule is entry type and turn distance, nothing else.** No line of text is ever read to
 * decide whether it stays (`Agents.md`, "semantic questions must not be hard-coded"): a `coc-capsule`
 * message goes because of its customType, a tool round trip goes because of its block types and its
 * distance from the last turn. What a sentence says never enters the decision.
 */

import type { CompactionEntry, SessionEntry } from "@earendil-works/pi-coding-agent";

/** The last two turns stay whole (contract §19.2). A "turn" starts at a context-visible user message. */
export const KEEP_TURNS = 2;

/** The capsule: one per player turn, regenerated by the kernel every turn, so every older one is a dead page. */
export const CAPSULE_TYPE = "coc-capsule";
/** The mechanics projection (contract §16.2): a front-end's JSON, never the Keeper's to read back. */
export const MECHANICS_TYPE = "coc-mechanics";
/** Host notes (recovery, steering, a refused delivery): short, and each one is about something still owed. */
export const HOST_TYPE = "coc-host";
/** `details.kind` of the note this extension itself posts after a fold; a later fold supersedes it. */
export const FOLD_NOTE_KIND = "compacted";

/** The fold record version, so a later shape change can tell an old compaction entry apart. */
export const FOLD_VERSION = 1;

/** One kept line of transcript. `who` comes from the entry's role, never from its text. */
export interface FoldLine {
	who: "player" | "keeper" | "host";
	text: string;
}

/** What went whole, counted by type. Reported in the summary so a human can see the fold worked. */
export interface FoldDropped {
	capsules: number;
	mechanics: number;
	tool_calls: number;
	tool_results: number;
}

/** Carried on the compaction entry so the next fold can pick the transcript up without re-reading a summary. */
export interface FoldDetails {
	coc_fold: {
		version: number;
		lines: FoldLine[];
		dropped: FoldDropped;
	};
}

export interface Fold {
	firstKeptEntryId: string;
	summary: string;
	details: FoldDetails;
	/** Index of the first kept entry, for telemetry and tests. */
	keptFrom: number;
	/** How many entries fell into the folded region. */
	folded: number;
	dropped: FoldDropped;
	lines: FoldLine[];
}

function textOfContent(content: unknown): string {
	if (typeof content === "string") return content.trim();
	if (!Array.isArray(content)) return "";
	return content
		.filter((block): block is { type: string; text: string } => {
			if (!block || typeof block !== "object") return false;
			const row = block as { type?: unknown; text?: unknown };
			return row.type === "text" && typeof row.text === "string";
		})
		.map((block) => block.text)
		.join("")
		.trim();
}

function hasToolCall(content: unknown): boolean {
	if (!Array.isArray(content)) return false;
	return content.some((block) => Boolean(block) && typeof block === "object" && (block as { type?: unknown }).type === "toolCall");
}

/**
 * The single classification step. It looks at the entry type, the message role and the block
 * types — never at any text. Everything the model would have seen is either kept as one
 * transcript line or counted as dropped; everything the model never sees (custom entries other
 * than the mechanics projection, labels, model changes) is simply not this fold's business.
 */
export function classify(entry: SessionEntry): { keep?: FoldLine; drop?: keyof FoldDropped } {
	if (entry.type === "custom_message") {
		if (entry.customType === CAPSULE_TYPE) return { drop: "capsules" };
		// The note this extension posts after a fold is about the previous fold, and the fold being
		// written now supersedes it. It is recognised by the `details.kind` this extension itself
		// minted, so this is still a type check and not a reading of what the note says.
		if (entry.customType === HOST_TYPE && (entry.details as { kind?: unknown } | undefined)?.kind === FOLD_NOTE_KIND) {
			return {};
		}
		// Every other host message survives: the kinds the kernel mints (recovery, steering, a
		// delivery the kernel refused) are all about an obligation that is still open, and deciding
		// which of them still matters would mean reading them.
		const text = textOfContent(entry.content);
		return text ? { keep: { who: "host", text } } : {};
	}
	if (entry.type === "custom") {
		// Custom entries never reach the model (`buildSessionContext` ignores them), so folding them
		// changes no context; the mechanics projection is counted anyway because §19.2 names it.
		return entry.customType === MECHANICS_TYPE ? { drop: "mechanics" } : {};
	}
	if (entry.type !== "message") return {};
	const message = entry.message as { role?: unknown; content?: unknown };
	if (message.role === "user") {
		const text = textOfContent(message.content);
		return text ? { keep: { who: "player", text } } : {};
	}
	if (message.role === "toolResult") return { drop: "tool_results" };
	if (message.role === "assistant") {
		// An assistant message carrying tool calls is a round trip, not a delivery: the kernel
		// extension has already stripped its text (contract §8), and the receipts are in the kernel.
		if (hasToolCall(message.content)) return { drop: "tool_calls" };
		const text = textOfContent(message.content);
		return text ? { keep: { who: "keeper", text } } : {};
	}
	return {};
}

/** Index of the entry that opens each turn: a context-visible user message, which is the player's input (contract §4). */
export function turnStarts(entries: SessionEntry[], from: number): number[] {
	const starts: number[] = [];
	for (let index = from; index < entries.length; index += 1) {
		const entry = entries[index];
		if (entry.type === "message" && (entry.message as { role?: unknown }).role === "user") starts.push(index);
	}
	return starts;
}

/**
 * Where the previous fold stopped. Compaction is iterative: `prepareCompaction` starts its own
 * boundary at the previous compaction's first kept entry, and so must this one, or entries an
 * earlier fold already folded would be pulled back into context and doubled in the summary.
 */
export function foldBoundary(entries: SessionEntry[]): { start: number; previous?: CompactionEntry } {
	for (let index = entries.length - 1; index >= 0; index -= 1) {
		const entry = entries[index];
		if (entry.type !== "compaction") continue;
		const kept = entries.findIndex((row) => row.id === entry.firstKeptEntryId);
		return { start: kept >= 0 ? kept : index + 1, previous: entry };
	}
	return { start: 0 };
}

/** The transcript an earlier fold kept, so this fold carries it forward rather than losing it. */
export function previousLines(previous: CompactionEntry | undefined): FoldLine[] {
	const details = previous?.details as FoldDetails | undefined;
	const rows = details?.coc_fold?.lines;
	if (!Array.isArray(rows)) return [];
	return rows.filter(
		(row): row is FoldLine =>
			Boolean(row) &&
			typeof row === "object" &&
			typeof (row as FoldLine).text === "string" &&
			(row as FoldLine).who !== undefined,
	);
}

const WHO_LABEL: Record<FoldLine["who"], string> = { player: "player", keeper: "keeper", host: "host" };

export function renderFold(lines: FoldLine[], dropped: FoldDropped): string {
	const body = lines.map((line) => `${WHO_LABEL[line.who]}: ${line.text}`).join("\n\n");
	return [
		"[COC context fold]",
		"Older turns were folded by entry type and turn distance only; no line was read to decide whether it stays.",
		`Dropped whole: ${dropped.capsules} turn capsules, ${dropped.mechanics} mechanics projections, ${dropped.tool_calls} tool calls and ${dropped.tool_results} tool results. Their receipts are in the kernel; ask for them with recall.`,
		"Kept below word for word: every player line, every delivered narration, every host note.",
		"",
		body || "(nothing was kept from the folded turns)",
		"",
		"The table state is not in this fold. The next turn's capsule carries the scene, the clock, who is present, the pressures and what is owed; use recall for anything older.",
	].join("\n");
}

export interface FoldRequest {
	/** The branch entries Pi is about to compact, oldest first. */
	entries: SessionEntry[];
	/** Pi's own cut, used only when the COC rule has nothing older than the last two turns to fold. */
	fallbackFirstKeptEntryId: string;
	keepTurns?: number;
}

/**
 * Fold one compaction. Returns undefined only when no cut point can be named at all, in which
 * case the caller lets Pi do whatever it would have done.
 */
export function foldContext(request: FoldRequest): Fold | undefined {
	const { entries } = request;
	const keepTurns = request.keepTurns ?? KEEP_TURNS;
	const boundary = foldBoundary(entries);
	const starts = turnStarts(entries, boundary.start);
	const fallbackIndex = entries.findIndex((entry) => entry.id === request.fallbackFirstKeptEntryId);

	// The start of the turn `keepTurns` back; with fewer turns than that, the earliest one this fold owns.
	let cut = starts.length >= keepTurns ? starts[starts.length - keepTurns] : (starts[0] ?? -1);
	if (cut <= boundary.start) {
		// Nothing older than the turns being kept: fall back to Pi's cut so the fold still shrinks
		// the context by at least as much as Pi asked for, and the table is never summarised by a model.
		cut = fallbackIndex;
	}
	if (cut < 0 || cut >= entries.length) return undefined;

	const dropped: FoldDropped = { capsules: 0, mechanics: 0, tool_calls: 0, tool_results: 0 };
	const lines: FoldLine[] = [...previousLines(boundary.previous)];
	for (let index = boundary.start; index < cut; index += 1) {
		const verdict = classify(entries[index]);
		if (verdict.drop) dropped[verdict.drop] += 1;
		if (verdict.keep) lines.push(verdict.keep);
	}
	return {
		firstKeptEntryId: entries[cut].id,
		summary: renderFold(lines, dropped),
		details: { coc_fold: { version: FOLD_VERSION, lines, dropped } },
		keptFrom: cut,
		folded: Math.max(0, cut - boundary.start),
		dropped,
		lines,
	};
}

/** The share of the context window at which the table compacts before a turn rather than inside one (contract §19.2). */
export const DEFAULT_COMPACT_AT = 0.7;

/**
 * The pre-emptive threshold, as a fraction. `PI_COC_COMPACT_AT` takes a percentage (70) or a
 * fraction (0.7); anything else, and the default stands. Read per call, never at module top level:
 * one process loads these extensions several times (docs/pi-host-contract.md §1).
 */
export function compactAt(): number {
	const raw = process.env.PI_COC_COMPACT_AT?.trim();
	if (!raw) return DEFAULT_COMPACT_AT;
	const value = Number(raw);
	if (!Number.isFinite(value) || value <= 0) return DEFAULT_COMPACT_AT;
	const fraction = value > 1 ? value / 100 : value;
	return fraction > 0 && fraction <= 1 ? fraction : DEFAULT_COMPACT_AT;
}
