/**
 * Generated by coc_mcp_contract_archive.py from canonical OperationSpec facts.
 * DO NOT EDIT. Regenerate through the integration-owned projection command.
 */
export const AUDIENCES = [
  "audit",
  "host",
  "keeper",
  "setup",
  "source_worker"
] as const;
export const PLAY_PHASES = [
  "cold_start",
  "ending",
  "live_turn",
  "opening",
  "pending_finalization",
  "recovery"
] as const;
export type PlayPhase = typeof PLAY_PHASES[number];
export const KP_SURFACES = [
  "advice",
  "context",
  "none",
  "npc",
  "rules",
  "setup",
  "state",
  "subsystem",
  "turn"
] as const;
export type KpSurface = typeof KP_SURFACES[number];
export const EXECUTION_CLASSES = [
  "parallel_read",
  "serial_campaign",
  "serial_global"
] as const;
export type ExecutionClass = typeof EXECUTION_CLASSES[number];
export type OperationPolicy = {
  audience: string;
  phases: readonly string[];
  contract: string;
  advisory: boolean;
  kp_surface: KpSurface;
  execution_class: ExecutionClass;
};
export const OPERATION_POLICY: Record<string, OperationPolicy> = {
  "actions.advise": {
    "advisory": true,
    "audience": "keeper",
    "contract": "advisory",
    "execution_class": "serial_campaign",
    "kp_surface": "advice",
    "phases": [
      "live_turn"
    ]
  },
  "actions.list": {
    "advisory": false,
    "audience": "keeper",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "context",
    "phases": [
      "opening",
      "live_turn",
      "pending_finalization"
    ]
  },
  "chase.context": {
    "advisory": false,
    "audience": "keeper",
    "contract": "rules",
    "execution_class": "serial_campaign",
    "kp_surface": "subsystem",
    "phases": [
      "live_turn",
      "pending_finalization"
    ]
  },
  "chase.execute": {
    "advisory": false,
    "audience": "keeper",
    "contract": "rules",
    "execution_class": "serial_campaign",
    "kp_surface": "subsystem",
    "phases": [
      "live_turn"
    ]
  },
  "clues.query": {
    "advisory": false,
    "audience": "keeper",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "context",
    "phases": [
      "opening",
      "live_turn",
      "pending_finalization"
    ]
  },
  "combat.context": {
    "advisory": false,
    "audience": "keeper",
    "contract": "rules",
    "execution_class": "serial_campaign",
    "kp_surface": "subsystem",
    "phases": [
      "live_turn",
      "pending_finalization"
    ]
  },
  "combat.end": {
    "advisory": false,
    "audience": "keeper",
    "contract": "rules",
    "execution_class": "serial_campaign",
    "kp_surface": "subsystem",
    "phases": [
      "live_turn"
    ]
  },
  "combat.resolve": {
    "advisory": false,
    "audience": "keeper",
    "contract": "rules",
    "execution_class": "serial_campaign",
    "kp_surface": "subsystem",
    "phases": [
      "live_turn"
    ]
  },
  "development.settle": {
    "advisory": false,
    "audience": "audit",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "none",
    "phases": [
      "ending"
    ]
  },
  "director.advise": {
    "advisory": true,
    "audience": "keeper",
    "contract": "advisory",
    "execution_class": "serial_campaign",
    "kp_surface": "advice",
    "phases": [
      "live_turn"
    ]
  },
  "epistemic.query": {
    "advisory": false,
    "audience": "keeper",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "context",
    "phases": [
      "opening",
      "live_turn",
      "pending_finalization"
    ]
  },
  "events.query": {
    "advisory": false,
    "audience": "keeper",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "context",
    "phases": [
      "live_turn",
      "pending_finalization",
      "recovery"
    ]
  },
  "evidence.record_adoption": {
    "advisory": false,
    "audience": "keeper",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "context",
    "phases": [
      "live_turn"
    ]
  },
  "evidence.table_opening": {
    "advisory": false,
    "audience": "keeper",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "context",
    "phases": [
      "opening"
    ]
  },
  "history.diff": {
    "advisory": false,
    "audience": "keeper",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "context",
    "phases": [
      "live_turn",
      "pending_finalization",
      "recovery"
    ]
  },
  "history.query": {
    "advisory": false,
    "audience": "keeper",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "context",
    "phases": [
      "live_turn",
      "pending_finalization",
      "recovery"
    ]
  },
  "mechanics.ensure": {
    "advisory": false,
    "audience": "keeper",
    "contract": "rules",
    "execution_class": "serial_campaign",
    "kp_surface": "subsystem",
    "phases": [
      "live_turn"
    ]
  },
  "memory.adjudicate": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "live_turn"
    ]
  },
  "memory.extraction_settle": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "live_turn",
      "pending_finalization",
      "recovery"
    ]
  },
  "memory.extraction_status": {
    "advisory": false,
    "audience": "keeper",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "context",
    "phases": [
      "live_turn",
      "pending_finalization",
      "recovery"
    ]
  },
  "memory.recall": {
    "advisory": false,
    "audience": "keeper",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "context",
    "phases": [
      "opening",
      "live_turn",
      "pending_finalization"
    ]
  },
  "narration.brief": {
    "advisory": true,
    "audience": "keeper",
    "contract": "advisory",
    "execution_class": "serial_campaign",
    "kp_surface": "advice",
    "phases": [
      "live_turn",
      "pending_finalization"
    ]
  },
  "narration.review": {
    "advisory": true,
    "audience": "keeper",
    "contract": "advisory",
    "execution_class": "serial_campaign",
    "kp_surface": "advice",
    "phases": [
      "live_turn",
      "pending_finalization"
    ]
  },
  "npc.advise": {
    "advisory": true,
    "audience": "keeper",
    "contract": "advisory",
    "execution_class": "serial_campaign",
    "kp_surface": "advice",
    "phases": [
      "live_turn"
    ]
  },
  "npc.query": {
    "advisory": false,
    "audience": "keeper",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "npc",
    "phases": [
      "opening",
      "live_turn",
      "pending_finalization"
    ]
  },
  "npc.reaction": {
    "advisory": false,
    "audience": "keeper",
    "contract": "rules",
    "execution_class": "serial_campaign",
    "kp_surface": "npc",
    "phases": [
      "live_turn"
    ]
  },
  "personal_horror.query": {
    "advisory": false,
    "audience": "keeper",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "context",
    "phases": [
      "opening",
      "live_turn",
      "pending_finalization"
    ]
  },
  "progressive.claim_host_work": {
    "advisory": false,
    "audience": "source_worker",
    "contract": "source_lifecycle",
    "execution_class": "serial_campaign",
    "kp_surface": "none",
    "phases": [
      "opening",
      "live_turn"
    ]
  },
  "progressive.follow_mentions": {
    "advisory": false,
    "audience": "keeper",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "setup",
    "phases": [
      "live_turn"
    ]
  },
  "progressive.fulfill_host_work": {
    "advisory": false,
    "audience": "source_worker",
    "contract": "source_lifecycle",
    "execution_class": "serial_campaign",
    "kp_surface": "none",
    "phases": [
      "opening",
      "live_turn"
    ]
  },
  "progressive.on_enter_scene": {
    "advisory": false,
    "audience": "keeper",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "setup",
    "phases": [
      "live_turn"
    ]
  },
  "progressive.opening_bootstrap": {
    "advisory": false,
    "audience": "keeper",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "setup",
    "phases": [
      "opening"
    ]
  },
  "progressive.prepare_opening": {
    "advisory": false,
    "audience": "keeper",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "setup",
    "phases": [
      "opening"
    ]
  },
  "progressive.project_opening": {
    "advisory": false,
    "audience": "host",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "none",
    "phases": [
      "opening"
    ]
  },
  "progressive.publish_skeleton": {
    "advisory": false,
    "audience": "source_worker",
    "contract": "source_lifecycle",
    "execution_class": "serial_campaign",
    "kp_surface": "none",
    "phases": [
      "opening",
      "live_turn"
    ]
  },
  "progressive.register_source_bundle": {
    "advisory": false,
    "audience": "host",
    "contract": "source_lifecycle",
    "execution_class": "serial_campaign",
    "kp_surface": "none",
    "phases": [
      "cold_start",
      "opening"
    ]
  },
  "progressive.release_host_work_leases": {
    "advisory": false,
    "audience": "source_worker",
    "contract": "source_lifecycle",
    "execution_class": "serial_campaign",
    "kp_surface": "none",
    "phases": [
      "opening",
      "live_turn"
    ]
  },
  "progressive.renew_host_work_leases": {
    "advisory": false,
    "audience": "source_worker",
    "contract": "source_lifecycle",
    "execution_class": "serial_campaign",
    "kp_surface": "none",
    "phases": [
      "opening",
      "live_turn"
    ]
  },
  "progressive.request_locator_pass": {
    "advisory": false,
    "audience": "host",
    "contract": "source_lifecycle",
    "execution_class": "serial_campaign",
    "kp_surface": "none",
    "phases": [
      "opening",
      "live_turn"
    ]
  },
  "progressive.request_mechanics": {
    "advisory": false,
    "audience": "keeper",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "setup",
    "phases": [
      "live_turn"
    ]
  },
  "progressive.request_opening_pack": {
    "advisory": false,
    "audience": "host",
    "contract": "source_lifecycle",
    "execution_class": "serial_campaign",
    "kp_surface": "none",
    "phases": [
      "opening"
    ]
  },
  "progressive.retry_full_parse": {
    "advisory": false,
    "audience": "host",
    "contract": "source_lifecycle",
    "execution_class": "serial_campaign",
    "kp_surface": "none",
    "phases": [
      "opening",
      "recovery"
    ]
  },
  "progressive.status": {
    "advisory": false,
    "audience": "host",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "none",
    "phases": [
      "opening",
      "live_turn",
      "recovery"
    ]
  },
  "quest.activate": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "opening",
      "live_turn",
      "pending_finalization"
    ]
  },
  "quest.improvise": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "opening",
      "live_turn",
      "pending_finalization"
    ]
  },
  "quest.map": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "opening",
      "live_turn",
      "pending_finalization"
    ]
  },
  "quest.offer": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "opening",
      "live_turn",
      "pending_finalization"
    ]
  },
  "quest.settle": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "opening",
      "live_turn",
      "pending_finalization"
    ]
  },
  "rules.build_scale": {
    "advisory": false,
    "audience": "keeper",
    "contract": "rules",
    "execution_class": "serial_campaign",
    "kp_surface": "rules",
    "phases": [
      "live_turn"
    ]
  },
  "rules.cash_assets": {
    "advisory": false,
    "audience": "keeper",
    "contract": "rules",
    "execution_class": "serial_campaign",
    "kp_surface": "rules",
    "phases": [
      "cold_start",
      "opening",
      "live_turn"
    ]
  },
  "rules.catalog_search": {
    "advisory": true,
    "audience": "keeper",
    "contract": "advisory",
    "execution_class": "serial_campaign",
    "kp_surface": "rules",
    "phases": [
      "cold_start",
      "opening",
      "live_turn"
    ]
  },
  "rules.check": {
    "advisory": false,
    "audience": "keeper",
    "contract": "rules",
    "execution_class": "serial_campaign",
    "kp_surface": "rules",
    "phases": [
      "live_turn"
    ]
  },
  "rules.damage": {
    "advisory": false,
    "audience": "keeper",
    "contract": "rules",
    "execution_class": "serial_campaign",
    "kp_surface": "rules",
    "phases": [
      "live_turn"
    ]
  },
  "rules.dying_check": {
    "advisory": false,
    "audience": "keeper",
    "contract": "rules",
    "execution_class": "serial_campaign",
    "kp_surface": "rules",
    "phases": [
      "live_turn"
    ]
  },
  "rules.first_aid": {
    "advisory": false,
    "audience": "keeper",
    "contract": "rules",
    "execution_class": "serial_campaign",
    "kp_surface": "rules",
    "phases": [
      "live_turn"
    ]
  },
  "rules.luck_spend": {
    "advisory": false,
    "audience": "keeper",
    "contract": "rules",
    "execution_class": "serial_campaign",
    "kp_surface": "rules",
    "phases": [
      "live_turn"
    ]
  },
  "rules.medicine": {
    "advisory": false,
    "audience": "keeper",
    "contract": "rules",
    "execution_class": "serial_campaign",
    "kp_surface": "rules",
    "phases": [
      "live_turn"
    ]
  },
  "rules.opposed": {
    "advisory": false,
    "audience": "keeper",
    "contract": "rules",
    "execution_class": "serial_campaign",
    "kp_surface": "rules",
    "phases": [
      "live_turn"
    ]
  },
  "rules.psychology_observe": {
    "advisory": false,
    "audience": "keeper",
    "contract": "rules",
    "execution_class": "serial_campaign",
    "kp_surface": "rules",
    "phases": [
      "live_turn"
    ]
  },
  "rules.push": {
    "advisory": false,
    "audience": "keeper",
    "contract": "rules",
    "execution_class": "serial_campaign",
    "kp_surface": "rules",
    "phases": [
      "live_turn"
    ]
  },
  "rules.resource_delta": {
    "advisory": false,
    "audience": "keeper",
    "contract": "rules",
    "execution_class": "serial_campaign",
    "kp_surface": "rules",
    "phases": [
      "live_turn"
    ]
  },
  "rules.roll": {
    "advisory": false,
    "audience": "keeper",
    "contract": "rules",
    "execution_class": "serial_campaign",
    "kp_surface": "rules",
    "phases": [
      "live_turn"
    ]
  },
  "rules.roll_dice": {
    "advisory": false,
    "audience": "keeper",
    "contract": "rules",
    "execution_class": "serial_campaign",
    "kp_surface": "rules",
    "phases": [
      "cold_start",
      "opening",
      "live_turn"
    ]
  },
  "rules.sanity_check": {
    "advisory": false,
    "audience": "keeper",
    "contract": "rules",
    "execution_class": "serial_campaign",
    "kp_surface": "rules",
    "phases": [
      "live_turn"
    ]
  },
  "rules.skill_describe": {
    "advisory": false,
    "audience": "keeper",
    "contract": "rules",
    "execution_class": "parallel_read",
    "kp_surface": "rules",
    "phases": [
      "live_turn"
    ]
  },
  "rules.social_adjudicate": {
    "advisory": false,
    "audience": "keeper",
    "contract": "rules",
    "execution_class": "serial_campaign",
    "kp_surface": "rules",
    "phases": [
      "live_turn"
    ]
  },
  "rules.weekly_recovery": {
    "advisory": false,
    "audience": "keeper",
    "contract": "rules",
    "execution_class": "serial_campaign",
    "kp_surface": "rules",
    "phases": [
      "live_turn"
    ]
  },
  "sanity.context": {
    "advisory": false,
    "audience": "keeper",
    "contract": "rules",
    "execution_class": "serial_campaign",
    "kp_surface": "subsystem",
    "phases": [
      "live_turn",
      "pending_finalization"
    ]
  },
  "sanity.execute": {
    "advisory": false,
    "audience": "keeper",
    "contract": "rules",
    "execution_class": "serial_campaign",
    "kp_surface": "subsystem",
    "phases": [
      "live_turn"
    ]
  },
  "scene.context": {
    "advisory": false,
    "audience": "keeper",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "context",
    "phases": [
      "opening",
      "live_turn",
      "pending_finalization"
    ]
  },
  "scene.map": {
    "advisory": false,
    "audience": "keeper",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "context",
    "phases": [
      "opening",
      "live_turn",
      "pending_finalization"
    ]
  },
  "secrets.briefing": {
    "advisory": false,
    "audience": "keeper",
    "contract": "module_secret",
    "execution_class": "serial_campaign",
    "kp_surface": "context",
    "phases": [
      "opening",
      "live_turn",
      "pending_finalization"
    ]
  },
  "session.begin": {
    "advisory": false,
    "audience": "host",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "none",
    "phases": [
      "cold_start",
      "recovery",
      "live_turn"
    ]
  },
  "session.continuation_detail": {
    "advisory": false,
    "audience": "host",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "none",
    "phases": [
      "cold_start",
      "recovery",
      "live_turn"
    ]
  },
  "session.delivery_ack": {
    "advisory": false,
    "audience": "host",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "none",
    "phases": [
      "cold_start",
      "recovery",
      "live_turn"
    ]
  },
  "session.delivery_text": {
    "advisory": false,
    "audience": "keeper",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "context",
    "phases": [
      "live_turn",
      "recovery"
    ]
  },
  "session.resume": {
    "advisory": false,
    "audience": "keeper",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "setup",
    "phases": [
      "cold_start",
      "opening",
      "recovery",
      "live_turn",
      "pending_finalization"
    ]
  },
  "setup.adopt_source_facts": {
    "advisory": false,
    "audience": "setup",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "setup",
    "phases": [
      "cold_start",
      "opening",
      "live_turn"
    ]
  },
  "setup.chargen_run": {
    "advisory": false,
    "audience": "setup",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "setup",
    "phases": [
      "cold_start",
      "opening",
      "live_turn"
    ]
  },
  "setup.complete": {
    "advisory": false,
    "audience": "setup",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "setup",
    "phases": [
      "cold_start",
      "opening",
      "live_turn"
    ]
  },
  "setup.inspect": {
    "advisory": false,
    "audience": "setup",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "setup",
    "phases": [
      "cold_start",
      "opening",
      "live_turn"
    ]
  },
  "setup.investigator_contract": {
    "advisory": false,
    "audience": "setup",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "setup",
    "phases": [
      "cold_start",
      "opening",
      "live_turn"
    ]
  },
  "setup.invoke": {
    "advisory": false,
    "audience": "setup",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "setup",
    "phases": [
      "cold_start",
      "opening",
      "live_turn"
    ]
  },
  "setup.phase": {
    "advisory": false,
    "audience": "setup",
    "contract": "none",
    "execution_class": "parallel_read",
    "kp_surface": "setup",
    "phases": [
      "cold_start",
      "opening",
      "live_turn"
    ]
  },
  "setup.quick_start": {
    "advisory": false,
    "audience": "setup",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "setup",
    "phases": [
      "cold_start",
      "opening",
      "live_turn"
    ]
  },
  "state.advance_time": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "live_turn"
    ]
  },
  "state.assets_liquidate": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "live_turn"
    ]
  },
  "state.backstory_corruption_add": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "live_turn"
    ]
  },
  "state.belief_apply": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "live_turn"
    ]
  },
  "state.cash_grant": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "live_turn"
    ]
  },
  "state.cash_query": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "live_turn"
    ]
  },
  "state.cash_semantic": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "cold_start",
      "opening",
      "live_turn"
    ]
  },
  "state.cash_spend": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "live_turn"
    ]
  },
  "state.clear_transient_condition": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "live_turn"
    ]
  },
  "state.clock_discontinuity": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "live_turn"
    ]
  },
  "state.deliver_handout": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "live_turn"
    ]
  },
  "state.end_session": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "live_turn"
    ]
  },
  "state.exceptional_effect": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "live_turn",
      "pending_finalization"
    ]
  },
  "state.finance_query": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "live_turn"
    ]
  },
  "state.inventory_list": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "live_turn",
      "pending_finalization",
      "opening"
    ]
  },
  "state.item_grant": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "live_turn"
    ]
  },
  "state.item_remove": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "live_turn"
    ]
  },
  "state.item_use": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "live_turn"
    ]
  },
  "state.journal": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "turn",
    "phases": [
      "live_turn",
      "pending_finalization",
      "recovery",
      "ending"
    ]
  },
  "state.mark_safe_rest": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "live_turn"
    ]
  },
  "state.move_scene": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "live_turn"
    ]
  },
  "state.npc_presence": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "live_turn"
    ]
  },
  "state.npc_update": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "live_turn"
    ]
  },
  "state.personal_horror_add": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "live_turn"
    ]
  },
  "state.personal_horror_mark_woven": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "live_turn"
    ]
  },
  "state.promote_scene": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "live_turn"
    ]
  },
  "state.purchase": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "live_turn"
    ]
  },
  "state.record_clue": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "live_turn"
    ]
  },
  "state.record_npc_engagement": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "live_turn"
    ]
  },
  "state.record_route_completion": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "live_turn"
    ]
  },
  "state.recover_pending_narration_draft": {
    "advisory": false,
    "audience": "host",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "none",
    "phases": [
      "pending_finalization",
      "recovery"
    ]
  },
  "state.replay_handout": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "live_turn"
    ]
  },
  "state.set_flag": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "live_turn"
    ]
  },
  "state.supersede_settlement": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "recovery",
      "live_turn",
      "pending_finalization"
    ]
  },
  "state.threat_tick": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "live_turn"
    ]
  },
  "state.time_appearance": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "live_turn"
    ]
  },
  "state.time_marker": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "live_turn"
    ]
  },
  "steward.deliver": {
    "advisory": false,
    "audience": "host",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "none",
    "phases": [
      "live_turn"
    ]
  },
  "steward.deliveries": {
    "advisory": false,
    "audience": "keeper",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "context",
    "phases": [
      "opening",
      "live_turn",
      "pending_finalization"
    ]
  },
  "steward.domain_put": {
    "advisory": false,
    "audience": "host",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "none",
    "phases": [
      "live_turn"
    ]
  },
  "steward.mark_consumed": {
    "advisory": false,
    "audience": "host",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "none",
    "phases": [
      "live_turn"
    ]
  },
  "steward.notebook": {
    "advisory": false,
    "audience": "keeper",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "context",
    "phases": [
      "opening",
      "live_turn",
      "pending_finalization"
    ]
  },
  "steward.notebook_pay": {
    "advisory": false,
    "audience": "host",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "none",
    "phases": [
      "live_turn"
    ]
  },
  "steward.notebook_put": {
    "advisory": false,
    "audience": "host",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "none",
    "phases": [
      "live_turn"
    ]
  },
  "steward.scene_bundle_put": {
    "advisory": false,
    "audience": "host",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "none",
    "phases": [
      "live_turn"
    ]
  },
  "steward.scene_supply": {
    "advisory": false,
    "audience": "keeper",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "context",
    "phases": [
      "opening",
      "live_turn",
      "pending_finalization"
    ]
  },
  "storylets.suggest": {
    "advisory": true,
    "audience": "keeper",
    "contract": "advisory",
    "execution_class": "serial_campaign",
    "kp_surface": "advice",
    "phases": [
      "live_turn"
    ]
  },
  "threat.query": {
    "advisory": false,
    "audience": "keeper",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "context",
    "phases": [
      "opening",
      "live_turn",
      "pending_finalization"
    ]
  },
  "timeline.confluence_confirm": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "live_turn",
      "pending_finalization",
      "recovery",
      "ending"
    ]
  },
  "timeline.confluence_query": {
    "advisory": false,
    "audience": "keeper",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "context",
    "phases": [
      "live_turn",
      "pending_finalization",
      "recovery",
      "ending"
    ]
  },
  "timeline.fork_confirm": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "live_turn"
    ]
  },
  "timeline.fork_request": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "live_turn"
    ]
  },
  "timeline.transfer": {
    "advisory": false,
    "audience": "keeper",
    "contract": "state",
    "execution_class": "serial_campaign",
    "kp_surface": "state",
    "phases": [
      "live_turn"
    ]
  },
  "transcript.locate": {
    "advisory": false,
    "audience": "keeper",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "context",
    "phases": [
      "live_turn",
      "recovery"
    ]
  },
  "transcript.read": {
    "advisory": false,
    "audience": "keeper",
    "contract": "none",
    "execution_class": "serial_campaign",
    "kp_surface": "context",
    "phases": [
      "live_turn",
      "recovery"
    ]
  },
  "turn.finalize": {
    "advisory": false,
    "audience": "keeper",
    "contract": "finalize",
    "execution_class": "serial_campaign",
    "kp_surface": "turn",
    "phases": [
      "live_turn",
      "pending_finalization",
      "recovery",
      "ending"
    ]
  },
  "turn.output_context": {
    "advisory": false,
    "audience": "keeper",
    "contract": "finalize",
    "execution_class": "serial_campaign",
    "kp_surface": "turn",
    "phases": [
      "live_turn",
      "pending_finalization",
      "recovery",
      "ending"
    ]
  }
};
export const OPERATIONS_BY_SURFACE: Record<Exclude<KpSurface, "none">, readonly string[]> = {
  "advice": [
    "actions.advise",
    "director.advise",
    "narration.brief",
    "narration.review",
    "npc.advise",
    "storylets.suggest"
  ],
  "context": [
    "actions.list",
    "clues.query",
    "epistemic.query",
    "events.query",
    "evidence.record_adoption",
    "evidence.table_opening",
    "history.diff",
    "history.query",
    "memory.extraction_status",
    "memory.recall",
    "personal_horror.query",
    "scene.context",
    "scene.map",
    "secrets.briefing",
    "session.delivery_text",
    "steward.deliveries",
    "steward.notebook",
    "steward.scene_supply",
    "threat.query",
    "timeline.confluence_query",
    "transcript.locate",
    "transcript.read"
  ],
  "npc": [
    "npc.query",
    "npc.reaction"
  ],
  "rules": [
    "rules.build_scale",
    "rules.cash_assets",
    "rules.catalog_search",
    "rules.check",
    "rules.damage",
    "rules.dying_check",
    "rules.first_aid",
    "rules.luck_spend",
    "rules.medicine",
    "rules.opposed",
    "rules.psychology_observe",
    "rules.push",
    "rules.resource_delta",
    "rules.roll",
    "rules.roll_dice",
    "rules.sanity_check",
    "rules.skill_describe",
    "rules.social_adjudicate",
    "rules.weekly_recovery"
  ],
  "setup": [
    "progressive.follow_mentions",
    "progressive.on_enter_scene",
    "progressive.opening_bootstrap",
    "progressive.prepare_opening",
    "progressive.request_mechanics",
    "session.resume",
    "setup.adopt_source_facts",
    "setup.chargen_run",
    "setup.complete",
    "setup.inspect",
    "setup.investigator_contract",
    "setup.invoke",
    "setup.phase",
    "setup.quick_start"
  ],
  "state": [
    "memory.adjudicate",
    "memory.extraction_settle",
    "quest.activate",
    "quest.improvise",
    "quest.map",
    "quest.offer",
    "quest.settle",
    "state.advance_time",
    "state.assets_liquidate",
    "state.backstory_corruption_add",
    "state.belief_apply",
    "state.cash_grant",
    "state.cash_query",
    "state.cash_semantic",
    "state.cash_spend",
    "state.clear_transient_condition",
    "state.clock_discontinuity",
    "state.deliver_handout",
    "state.end_session",
    "state.exceptional_effect",
    "state.finance_query",
    "state.inventory_list",
    "state.item_grant",
    "state.item_remove",
    "state.item_use",
    "state.mark_safe_rest",
    "state.move_scene",
    "state.npc_presence",
    "state.npc_update",
    "state.personal_horror_add",
    "state.personal_horror_mark_woven",
    "state.promote_scene",
    "state.purchase",
    "state.record_clue",
    "state.record_npc_engagement",
    "state.record_route_completion",
    "state.replay_handout",
    "state.set_flag",
    "state.supersede_settlement",
    "state.threat_tick",
    "state.time_appearance",
    "state.time_marker",
    "timeline.confluence_confirm",
    "timeline.fork_confirm",
    "timeline.fork_request",
    "timeline.transfer"
  ],
  "subsystem": [
    "chase.context",
    "chase.execute",
    "combat.context",
    "combat.end",
    "combat.resolve",
    "mechanics.ensure",
    "sanity.context",
    "sanity.execute"
  ],
  "turn": [
    "state.journal",
    "turn.finalize",
    "turn.output_context"
  ]
};
