/**
 * Generated by coc_text_graph.py from the TextGraph.
 * DO NOT EDIT. Regenerate with:
 *   python plugins/coc-keeper/scripts/coc_text_graph.py project --write
 */
export const OBLIGATION_ID_PREFIXES = [
  "first-impression:",
  "roll:",
  "sanity_bout:"
] as const;
export const OBLIGATION_KINDS = [
  "first-impression",
  "roll",
  "sanity_bout"
] as const;
export const AGENCY_CLAIM_TYPES = [
  "forced_behavior",
  "involuntary_physiology",
  "voluntary_action",
  "voluntary_active_emotion",
  "voluntary_belief",
  "voluntary_plan",
  "voluntary_speech",
  "voluntary_trust"
] as const;
export const VOLUNTARY_CLAIM_TYPES = [
  "voluntary_action",
  "voluntary_active_emotion",
  "voluntary_belief",
  "voluntary_plan",
  "voluntary_speech",
  "voluntary_trust"
] as const;
export const REALIZATION_VALUES = [
  "concealed_no_player_visible_beat",
  "fictional_beat"
] as const;
export const COVERAGE_FIELDS = [
  "action_realization",
  "causal_explanation",
  "exact_excerpt",
  "exceptional_beat",
  "obligation_id",
  "persona_fit",
  "player_input_handling",
  "realization",
  "response"
] as const;
export const PLAYER_INPUT_HANDLING_VALUES = [
  "abstract_completed",
  "not_applicable",
  "specific_preserved"
] as const;
