/**
 * Generated by coc_text_graph.py from the TextGraph obligation plane.
 * DO NOT EDIT. Regenerate with:
 *   python plugins/coc-keeper/scripts/coc_text_graph.py project --write
 */
export const OBLIGATION_ID_PREFIXES = [
  "first-impression:",
  "roll:",
  "sanity_bout:"
] as const;
export const OBLIGATION_KINDS = [
  "first-impression",
  "roll",
  "sanity_bout"
] as const;
