/** Closed transaction metadata, shared by the existing action reviewers. No action is inferred here. */
export const HANDOVER_GROUND_NOTE = 'handover states the consent ground of an ownership transfer: given means both sides were willing and no dice were asked; taken means one side\'s leave was neither sought nor needed; check cites an already-settled roll. It does not specify a physical gesture. Putting a thing down is distinct from transferring ownership; judge the declared actor, recipient or place and consent, not an invented hand-to-hand requirement.';

/**
 * Shared semantic boundary for the admission questions (the lane's prompt, the v1 rules and the role-first choice
 * question); the model judges it in context, with the paired real-table lines as examples, never as a matcher.
 *
 * Contract §197.4 (2026-10-08): the 2026-10-08 boundary (ab81805b2), written for TR-F turn 3 -- the player told the captain
 * he would leave for the farm today while asking names, and the table moved him -- read only one direction, and from that
 * App on the reviewers read the player's own narration of a trip as a "plan" and refused it (TR-F2 run 2 turns 3 and 16,
 * real table run 3 turn 9). It now says both directions.
 */
export const PLAYER_EXECUTION_CHOICE_NOTE = `Read the complete player contribution in context and tell two things apart. (1) The player narrating what their investigator does -- now, next, or as a sequence of steps laid out in order -- is execution: every step is chosen, in its order, and a later step is carried out once the earlier ones have happened. Future tense, "then", "on arrival" or "first ... then" in the player's own narration do not turn it into a plan. Asking someone in the scene to do something chooses that request now. A conditional the player sets is executed when its condition is met in the fiction, and not when it is not. Examples from real tables, all execution: "I put the papers away, take the earliest ride to State Farm No. 3, and when I get there I first look for the production supervisor" chooses the trip now and the search for him on arrival; "Then let's go. I'm going to the Abramov house at the north end now and knocking" chooses the walk and the knock; "I ask the records clerk to pull the deed register for the Corbitt house" chooses that request. (2) What the investigator says to someone in the fiction about a future act -- a plan, promise, threat, bluff or hypothetical spoken to another person -- or text quoted from a document establishes the speech, not the physical act described. Example from a real table, speech: turning the denunciation letter over, the investigator asks the captain who wrote it and which family it names, and tells him "I will set out for the farm today": the examination and the questions are chosen, departure is not. A spoken threat can choose a social act, and a spoken promise can establish that promise, without authorizing the threatened attack or the promised payment. Dialogue such as "Let's go now" can choose immediate departure in context; quotation marks alone decide nothing. Respect explicit order, conditions and holding back; accompanying questions do not defer a clearly chosen current action. Speech about future execution is not_authorized for that execution; genuine ambiguity is uncertain.`;
