const TOOL_DESCRIPTIONS_ZH: Record<string, string> = {
  read: '读取文本文件或图片，并按需返回指定范围。',
  bash: '执行一次性 Shell 命令、构建、测试或脚本。',
  edit: '用精确文本替换修改现有文件。',
  write: '创建新文件或完整覆写文件。',
  grep: '在文件中按文本或正则搜索匹配位置。',
  find: '按文件名模式查找目录中的文件。',
  ls: '列出一个或多个目录的内容。',
  git: '只读查看 Git 状态、差异、提交记录和提交内容。',
  web_search: '搜索互联网并返回相关结果。',
  browser_search: '通过内置浏览器搜索网页。',
  browser_fetch: '通过内置浏览器读取网页内容。',
  fetch_content: '抓取网页、仓库、视频或其他 URL 的可读内容。',
  source_check: '用网页来源核验一条事实或结论。',
  get_search_content: '读取前一次搜索或抓取结果中的指定内容片段。',
  arxiv_fetch: '读取 arXiv 论文的元数据与正文。',
  browser: '控制 PipiUI 内置浏览器进行导航、点击、输入和观察。',
  browser_flow: '保存、查看和重放可复用的浏览器操作流程。',
  computer: '控制当前固定的 macOS 应用窗口。',
  open_application: '启动或切换到指定的 macOS 应用。',
  terminal: '操作需要长期存活或交互输入的可见终端。',
  image_gen: '根据文字描述生成图片。',
  image_edit: '根据参考图片执行编辑或风格转换。',
  generate_image: '根据文字描述生成图片。',
  pipiui_firecrawl_anydoc: '在本地解析 Word、OpenDocument、RTF、EPUB 或 CSV 文档。',
  list_open_documents: '列出当前聊天文档面板中已打开的文件。',
  secret_vault_put: '把密钥安全保存到 App 级 Secret Vault。',
  secret_vault_list: '列出 Vault 中的密钥元数据和当前挂载。',
  secret_vault_mount: '把 Vault 密钥挂载为当前会话环境变量。',
  secret_vault_unmount: '解除当前会话中的密钥挂载。',
  secret_vault_delete: '永久删除 Vault 中的密钥。',
  memory_query: '只读查询持久记忆后端。',
  memory_status: '检查持久记忆后端是否可用。',
  memory_search: '搜索跨会话保存的用户、项目或失败经验。',
  memory_add: '新增一条跨会话持久记忆。',
  memory_replace: '替换已有的持久记忆。',
  memory_remove: '删除已有的持久记忆。',
  session_search: '搜索以前的 Pi 会话内容。',
  session_recall: '读取当前会话中被压缩移出的历史片段。',
  skill_search: '按关键词查找已安装 Skill，并读取其说明。',
  skill_load: '按名称加载一个 Skill 的完整工作流程。',
  skill_manage: '创建、查看、更新或删除可复用 Skill。',
  subagent: '派出一个或一组独立 Subagent 任务。',
  subagent_chain: '按依赖顺序运行多步 Subagent 链。',
  subagent_status: '查看 Subagent 的运行、排队和完成状态。',
  subagent_abort: '中止指定的一次 Subagent 运行。',
  subagent_resolve: '关闭已终止的失败、中止或中断记录。',
  subagent_progress: '把 Subagent 的进度观察切换到指定日志。',
  subagent_watch: '订阅 Subagent 状态变化，避免重复轮询。',
  subagent_manage: '查看、校验、生成或安装 Agent 定义。',
  secretary_commit: '由收尾 Secretary 审核并提交已接受的文件。',
  ledger_note: '把关键决策、结果或风险追加到 Boss ledger。',
  context_doc: '写入多个 Subagent 共用的上下文文档。',
  context_manage: '检查并折叠可安全压缩的工具结果。',
  recall_folded: '临时读取已折叠上下文中的指定片段。',
  unfold: '把指定的折叠上下文永久展开回当前会话。',
  plan_publish: '发布结构化执行计划。',
  plan_approve: '把用户已批准的计划标记为可执行。',
  plan_cancel: '取消当前计划。',
  plan_task_update: '更新计划中单个任务的状态。',
  plan_check: '查看当前计划、任务与 Subagent 的对应状态。',
  code_search: '按描述定位最可能相关的代码片段。',
  code_nav: '查询符号定义、引用、调用者或实现关系。',
  repo_map: '快速生成仓库结构、符号和调用关系地图。',
  read_spans: '读取代码检索结果中选定片段的完整内容。',
  pipiui_runtime_info: '读取当前 Pi 会话的模型、工具和上下文状态。',
  goal_complete: '标记当前 Goal 已完成。',
  goal_blocked: '标记当前 Goal 被外部条件阻塞。',
  goal_wait: '让当前 Goal 等待外部事件或后台结果。',
  x_search: '使用模型提供商的原生 X 搜索能力。',
  code_interpreter: '在提供商托管环境中运行代码并处理数据。',
}

const SKILL_DESCRIPTIONS_ZH: Record<string, string> = {
  'add-extension': '为 PipiUI 添加或接入一个可插拔扩展。',
  'ask-matt': '通过结构化提问获得面向实现的专家式建议。',
  'browser-operator': '规划并执行可靠的浏览器自动化操作。',
  'chatrpg-test-dispatch': '拆分并派发 ChatRPG 的测试与验收任务。',
  'claude-handoff': '整理可交给 Claude 或其他 Agent 继续工作的上下文。',
  'code-review': '按正确性、质量、安全性和范围进行代码审查。',
  'codebase-design': '分析并设计代码库的模块边界与结构。',
  'create-pipiui-extension': '创建符合 PipiUI 约定的新扩展。',
  'create-subagent': '创建、校验和安装新的 Subagent 定义。',
  'diagnosing-bugs': '用可复现证据定位并修复软件缺陷。',
  'domain-modeling': '梳理业务概念、状态和领域边界。',
  'git-guardrails-claude-code': '为 Git 操作建立安全边界和检查规则。',
  'grill-me': '通过连续追问澄清尚未确定的产品或技术决策。',
  'grill-with-docs': '结合现有文档，通过追问补齐需求和约束。',
  grilling: '用结构化问题澄清关键决策，并给出推荐答案。',
  handoff: '生成清晰、可续接的任务交接说明。',
  implement: '按照已确定的目标完成实现、验证和收尾。',
  'improve-codebase-architecture': '识别并改进代码库中真实存在的架构问题。',
  'implement-spec': '按任务图并行实现整份规格：工人各占工作树，合并后统一评审，落成一个 PR。',
  'loop-me': '按反馈循环持续执行、检查和修正任务。',
  'migrate-to-shoehorn': '把现有流程迁移到 Shoehorn 工作方式。',
  'pipiui-research': '针对 PipiUI 代码、运行时和产品行为开展研究。',
  prototype: '快速制作可验证交互或技术方向的原型。',
  research: '围绕明确问题收集证据并形成结论。',
  retro: '复盘一次编码会话，提出对导航、检查、标准、工具经济性等环境层面的改进。',
  'resolving-merge-conflicts': '分析并安全解决 Git 合并冲突。',
  'scaffold-exercises': '为教学或练习内容生成可运行的脚手架。',
  'setup-matt-pocock-skills': '安装并配置 Matt Pocock 风格的技能集合。',
  'setup-pre-commit': '配置并验证 pre-commit 检查流程。',
  'setup-ts-deep-modules': '为 TypeScript 项目设置深模块边界和约束。',
  tdd: '按测试驱动开发流程先建立失败用例，再实现并重构。',
  teach: '把知识整理成可理解、可练习的教学过程。',
  'to-questionnaire': '把模糊需求转换成结构化问题清单。',
  'to-spec': '把已澄清需求整理成可执行规格。',
  'to-tickets': '把规格拆分成可独立执行的任务条目。',
  triage: '对问题进行归类、排序并确定下一步处理方式。',
  'wait-what': '在信息矛盾或上下文缺失时停下来核对真实意图。',
  wayfinder: '在陌生代码库中定位入口、模块和实现路径。',
  wizard: '用分步向导完成需要多个选择的配置或创建流程。',
  'writing-beats': '设计叙事节拍、场景推进和情绪转折。',
  'writing-for-agents': '编写适合 Agent 准确执行的指令和上下文。',
  'writing-fragments': '生成和整理可组合的短篇文字片段。',
  'writing-shape': '规划文章、故事或说明文的整体结构。',
}

const ROLE_DESCRIPTIONS_ZH: Record<string, string> = {
  boss: '当前主会话的总控 Agent：理解用户目标、执行主线工作，并把独立侧任务交给 Subagent。',
  supervisor: '后台管理 Agent：观察 Subagent 的状态、超时和异常信号，不直接执行普通工作。',
  'memory-review': 'Hermes 记忆复核角色：整理并复核会话记忆，不参与 Subagent fallback。',
  explore: '只读调研 Agent：搜索网页和仓库、读取文件并运行检查命令，但不修改文件。',
  'general-purpose': '通用实现 Agent：在隔离 worktree 中完成代码修改、验证和故障修复。',
  reviewer: '只读审查 Agent：判断实现是否正确、是否偏离目标，并检查质量与安全风险。',
  secretary: '收尾 Secretary：核对结果、工作树、验证和遗留文件，并通过受控入口创建提交。',
}

export function toolDescriptionZh(name: string): string {
  return TOOL_DESCRIPTIONS_ZH[name] ?? `运行时提供的「${name}」工具，用于完成对应的专项操作。`
}

export function skillDescriptionZh(name: string): string {
  return SKILL_DESCRIPTIONS_ZH[name] ?? `按需加载的「${name}」Skill，用于提供对应任务的专项流程。`
}

export function roleDescriptionZh(name: string): string {
  return ROLE_DESCRIPTIONS_ZH[name] ?? `自定义 Subagent「${name}」：按照该角色定义执行专项任务。`
}
