/** T12 typed fulfillment through the real SDK/TaskHost/dispatcher path. Controlled evidence is conformance only. */
import assert from "node:assert/strict";
import { existsSync } from "node:fs";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { setTimeout as settle } from "node:timers/promises";
import { spawnSync } from "node:child_process";
import { test } from "node:test";
import { fauxAssistantMessage, fauxProvider, fauxToolCall } from "@earendil-works/pi-ai";
import { createAgentSession, DefaultResourceLoader, ModelRuntime, SessionManager, SettingsManager } from "./pi.mjs";
import kernelExtension from "../../extensions/kernel/index.ts";
import { bindDecisionAnswers } from "../../runtime/jev/contracts.ts";
import { createTaskHostAdapter, DEFAULT_TASK_DEADLINE_MS, taskDeadlineMs } from "../../runtime/jev/task-host-session.ts";
import { FAKE_KERNEL } from "./harness.mjs";

class Store { records=new Map();async load(id){return structuredClone(this.records.get(id));}async save(record){this.records.set(record.checkpoint.context.id,structuredClone(record));} }
function setEnv(values){const prior=new Map();for(const[k,v]of Object.entries(values)){prior.set(k,process.env[k]);if(v===undefined)delete process.env[k];else process.env[k]=v;}return()=>{for(const[k,v]of prior)v===undefined?delete process.env[k]:process.env[k]=v;};}
const plan={goal:"Collect the exact 30 USD payment now.",subgoals:[],constraints:["No invented amount or payer."],evidenceRequired:["The exact due cash promise and condition receipt."],completion:["Canonical cash apply settles once."],capabilities:["apply"],replanWhen:[],returnWhen:[]};
function decide(batch){const raw=Object.fromEntries(batch.questions.map(q=>{let choice;if(q.key==="promise:0")choice="inspect";else if(q.key==="due")choice="due";else if(q.key==="terms")choice="finite";else if(q.key==="amount_shape")choice="fixed";else if(q.key==="condition:0")choice="supports";else if(q.key==="kind")choice=batch.state.selected_terms?.length?"done":"cash";else if(q.key==="beneficiary")choice="beneficiary:0";else if(q.key==="payer")choice="payer:0";else if(q.key==="total")choice="total:0";else if(q.key==="currency")choice="currency:0";else if(q.key==="allocation")choice="remaining";else if(q.key==="complete")choice="supported";else choice=Object.keys(q.criteria)[0];return[q.key,{status:"answered",type:"choice",choice,probabilities:Object.fromEntries(Object.keys(q.criteria).map(key=>[key,key===choice?1:0]))}];}));return bindDecisionAnswers(batch,raw,{inputTokens:1,outputTokens:1,costUsd:0});}

test("typed fulfillment keeps coordinates private and sends exact prepared effects plus metadata through one normal apply",async t=>{
	const cwd=await mkdtemp(join(tmpdir(),"jev-fulfillment-host-")),proxy=join(cwd,"proxy.mjs"),log=join(cwd,"proxy.jsonl"),kernelLog=join(cwd,"kernel.jsonl");
	const privateBinding={binding:{version:1,promiseId:"private-promise-id",promiseRefs:[{private:"source-ref"}],scope:{campaign:"fulfillment-host",worldline:"main",loop:0},terms:[{private:"term"}],digest:"private-digest",conditionReceipts:["private-receipt"],coverage:{complete:true,used:[{private:"source-ref"}],omitted:[]}},effects:[{effect:0,term:0}]};
	await writeFile(proxy,`import{spawn}from"node:child_process";import{appendFile}from"node:fs/promises";import{createInterface}from"node:readline";const child=spawn(process.execPath,[${JSON.stringify(FAKE_KERNEL)},...process.argv.slice(2)],{env:process.env,stdio:["pipe","pipe","inherit"]}),wait=[];createInterface({input:child.stdout}).on("line",line=>wait.shift()?.(JSON.parse(line)));const forward=r=>new Promise(ok=>{wait.push(ok);child.stdin.write(JSON.stringify(r)+"\\n")});let world="world-r1";const patch=v=>{if(!v||typeof v!=="object")return;if(v._context)Object.assign(v._context,{world_revision:world,task_world_revision:world,source_revision:"source-r1",task_source_revision:"source-r1"});for(const c of Object.values(v))patch(c)};for await(const line of createInterface({input:process.stdin})){const r=JSON.parse(line);await appendFile(${JSON.stringify(log)},JSON.stringify({method:r.method,params:r.params})+"\\n");let x;if(r.method==="table.apply.options")x={id:r.id,ok:true,result:{version:1,candidates:[],promises:[{alias:"promise:0",statement:"I will pay 30 USD when the work is completed."}],private_promises:{"promise:0":"private-promise-id"},revision:"apply-r1",world_revision:world,context:{scene:"office",pending_choice:null,session:null,present:["Steven Knott"],current_receipts:[]}}};else if(r.method==="table.fulfillment.options")x={id:r.id,ok:true,result:{version:1,snapshot:"private-snapshot",revision:"catalog-r1",world_revision:world,catalog:{promises:[{alias:"promise:0",statement:"I will pay 30 USD when the work is completed.",subject:"Steven Knott",scalars:[{alias:"total:0",text:"30",value:"30",kind:"token"}],original_context:[{role:"keeper",text:"I will pay 30 USD when the work is completed.",omitted:false}],fulfillment:{status:"open",terms:[]}}],beneficiaries:[{alias:"beneficiary:0",name:"Thomas Hayes",currencies:[{alias:"currency:0",name:"USD"}]}],payers:[{alias:"payer:0",name:"Steven Knott"}],objects:[],conditions:[{alias:"condition:0",description:{kind:"time",minutes:1}}],allocations:[],unavailable:[]}}};else if(r.method==="table.fulfillment.prepare")x={id:r.id,ok:true,result:{effects:[{kind:"cash",subject:"Thomas Hayes",with:"Steven Knott",source:"quote",currency:"USD",delta:30}],bindings:{fulfillments:[${JSON.stringify(privateBinding)}]},revision:"prepared-r1",world_revision:world}};else if(r.method==="table.apply"){world="world-r2";x={id:r.id,ok:true,result:{receipt:"cash:t1-c1",receipts:["cash:t1-c1"],effects:[],_task_advance:{campaign:"fulfillment-host",turn:1,worldline:"main",loop:0,operationId:r.params.call_id,receiptIds:["cash:t1-c1"],before:"broad-r1",after:"broad-r2",task_before:"world-r1",task_after:"world-r2"}}};}else{x=await forward(r);patch(x.result);}process.stdout.write(JSON.stringify(x)+"\\n")}child.kill();`,"utf8");
	const checked=spawnSync(process.execPath,["--check",proxy],{encoding:"utf8"});assert.equal(checked.status,0,checked.stderr);
	const hidden=Object.fromEntries(Object.keys(process.env).filter(k=>/(_API_KEY|_TOKEN|_SECRET)$/.test(k)).map(k=>[k,undefined])),restore=setEnv({...hidden,PI_COC_KERNEL_CMD:JSON.stringify([process.execPath,proxy]),PI_COC_CAMPAIGN:"fulfillment-host",PI_COC_MODE:"play",PI_COC_MEMORY_BACKFILL:"0",PI_COC_MODS_WAIT_MS:"0",PI_COC_ADMISSION_MODEL:"admission/a1",PI_OFFLINE:"1",FAKE_KERNEL_LOG:kernelLog,FAKE_KERNEL_WORKSPACE:"1"});
	const keeper=fauxProvider({provider:"fulfillment-host-provider",models:[{id:"keeper",reasoning:false}]});keeper.setResponses([fauxAssistantMessage([fauxToolCall("submit_plan_packet",plan)],{stopReason:"toolUse"}),fauxAssistantMessage([fauxToolCall("narrate",{text:"The exact payment is handed over."})],{stopReason:"toolUse"})]);const admission=fauxProvider({provider:"admission",models:[{id:"a1",reasoning:false}]});admission.setResponses([fauxAssistantMessage(JSON.stringify({verdict:"authorized",grounds:"The player requested the exact due payment."}))]);
	const runtime=await ModelRuntime.create({authPath:join(cwd,"auth.json"),modelsPath:null,modelsStorePath:join(cwd,"models.json"),refreshOnCreate:false});runtime.registerNativeProvider(keeper.provider);runtime.registerNativeProvider(admission.provider);const settings=SettingsManager.inMemory({compaction:{enabled:false},retry:{enabled:false}}),manager=SessionManager.inMemory(cwd),store=new Store(),batches=[],hooks=[],control={};let session;const adapter=createTaskHostAdapter(()=>session,{async decide(batch){batches.push(structuredClone(batch));return decide(batch);}},{applyEnabled:true,store});const mods={async prepare(method,payload){if(method==="apply")mods.payload=structuredClone(payload);},async after(){}};
	const probe={name:"fulfillment-host-probe",factory(pi){control.api=pi;pi.events.on("coc:kernel-bridge",v=>{control.bridge=v;});pi.events.on("coc:operation-dispatcher",v=>{control.dispatcher=v;});pi.events.on("coc:capsule",v=>{control.capsule=v;const c=v?.context??v?.capsule?._context??{};v.context={campaign:"fulfillment-host",worldline:"main",loop:0,turn:v.turn??1,source_revision:"source-r1",task_source_revision:"source-r1",world_revision:"world-r1",task_world_revision:"world-r1",...structuredClone(c)};});pi.on("session_start",()=>pi.events.emit("coc:mods-bridge",mods));pi.on("tool_call",e=>hooks.push({type:"tool_call",id:e.toolCallId,name:e.toolName,input:structuredClone(e.input)}));pi.on("tool_result",e=>hooks.push({type:"tool_result",id:e.toolCallId,name:e.toolName,input:structuredClone(e.input)}));}};
	const loader=new DefaultResourceLoader({cwd,agentDir:join(cwd,"agent"),settingsManager:settings,extensionFactories:[probe,{name:"kernel",factory:kernelExtension},{name:"task-host",factory:adapter.extension}]});await loader.reload();const created=await createAgentSession({cwd,agentDir:join(cwd,"agent"),model:keeper.getModel("keeper"),modelRuntime:runtime,thinkingLevel:"off",noTools:"builtin",resourceLoader:loader,sessionManager:manager,settingsManager:settings});session=created.session;const errors=[...created.extensionsResult.errors];await session.bindExtensions({mode:"rpc",onError:e=>errors.push(e)});t.after(async()=>{try{if(session._extensionRunner?.hasHandlers?.("session_shutdown"))await session._extensionRunner.emit({type:"session_shutdown",reason:"quit"});session.dispose();}finally{restore();await settle(50);await rm(cwd,{recursive:true,force:true,maxRetries:5,retryDelay:50});}});
	if(!control.capsule&&control.bridge?.call){const value=await control.bridge.call("table.capsule",{campaign:"fulfillment-host"});const c=value._context??{};control.api.events.emit("coc:capsule",{campaign:"fulfillment-host",turn:Number(c.turn??1),epoch:"fixture",capsule:value,context:c});}
	assert.ok(control.bridge?.call&&control.dispatcher&&control.capsule,JSON.stringify({control,errors,messages:session.messages}));
	const began=Date.now();await session.prompt("Please fulfill the exact 30 USD promise now.",{source:"rpc"});const task=adapter.status().task,calls=existsSync(log)?(await readFile(log,"utf8")).split("\n").filter(Boolean).map(JSON.parse):[];assert.deepEqual(errors,[]);assert.equal(task.status,"closed");assert.equal(task.reason,"delivered");assert.deepEqual(task.observations.map(row=>row.proposal.operation),["apply.options","apply.fulfillment.options","apply.fulfillment.prepare","apply"]);assert.ok(task.checkpoint.context.budget.deadlineAt>=began+DEFAULT_TASK_DEADLINE_MS&&task.checkpoint.context.budget.deadlineAt<=began+DEFAULT_TASK_DEADLINE_MS+1000);assert.equal(taskDeadlineMs(undefined),DEFAULT_TASK_DEADLINE_MS);assert.equal(taskDeadlineMs("30000"),30000);assert.throws(()=>taskDeadlineMs("3600001"),error=>error?.code==="invalid_task_deadline");
	const apply=calls.find(row=>row.method==="table.apply");assert.deepEqual(apply.params.effects,[{kind:"cash",subject:"Thomas Hayes",with:"Steven Knott",source:"quote",currency:"USD",delta:30}]);assert.deepEqual(apply.params._fulfillments,[privateBinding]);assert.equal(calls.filter(row=>row.method==="table.apply").length,1);const proposal=task.observations.at(-1).proposal;assert.deepEqual(proposal.args,{effects:apply.params.effects});assert.deepEqual(proposal.bindings,{fulfillments:[privateBinding]});assert.equal("_fulfillments"in mods.payload,false);const applyHooks=hooks.filter(row=>row.id===proposal.id);assert.deepEqual(applyHooks.map(row=>row.type),["tool_call","tool_result"]);assert.equal(JSON.stringify(applyHooks).includes("private-promise-id"),false);
	const modelText=session.messages.filter(row=>row.role==="toolResult"&&row.toolName==="submit_plan_packet").flatMap(row=>row.content??[]).filter(block=>block.type==="text").map(block=>block.text).join("");for(const hiddenValue of ["private-promise-id","private-snapshot","private-ref","private-digest","source_ref",'"delta":30'])assert.equal(modelText.includes(hiddenValue),false,hiddenValue);assert.ok(batches.every(batch=>!JSON.stringify(batch).includes("private-promise-id")));
});
