/** Generated by build-runtime.mjs from engine-owned clock declarations. */
import type {ClockEngine} from './worldline/reset.js';
import * as engine0 from './chase/model.js';
import * as engine1 from './combat/engine.js';
import * as engine2 from './development/state.js';
import * as engine3 from './healing/mp.js';
import * as engine4 from './healing/session.js';
import * as engine5 from './magic/state.js';
import * as engine6 from './sanity/session.js';
export const clockEngines: readonly ClockEngine[] = Object.freeze([
  {name:"chase/model.ts",paths:engine0.CLOCK_SAVE_PATHS,rebase:engine0.rebaseClock},
  {name:"combat/engine.ts",paths:engine1.CLOCK_SAVE_PATHS,rebase:engine1.rebaseClock},
  {name:"development/state.ts",paths:engine2.CLOCK_SAVE_PATHS,rebase:engine2.rebaseClock},
  {name:"healing/mp.ts",paths:engine3.CLOCK_SAVE_PATHS,rebase:engine3.rebaseClock},
  {name:"healing/session.ts",paths:engine4.CLOCK_SAVE_PATHS,rebase:engine4.rebaseClock},
  {name:"magic/state.ts",paths:engine5.CLOCK_SAVE_PATHS,rebase:engine5.rebaseClock},
  {name:"sanity/session.ts",paths:engine6.CLOCK_SAVE_PATHS,rebase:engine6.rebaseClock},
]);
