import type { DomainEvent, FictionTime, IdGenerator, JsonValue, RngReceipt, RuleRequest, RuleResolution } from "../../contracts/src/index.js";

export type RuleExecutionMode="deterministic"|"hybrid"|"keeper_judgment";
export interface RuleGraphNode{id:string;kind:string;domain?:string;layer?:string;execution?:RuleExecutionMode;enabled_by_default?:boolean;source_refs?:unknown[];[key:string]:unknown;}
export interface RuleGraphEdge{id:string;source:string;relation:string;target:string;[key:string]:unknown;}
export interface RuleGraphDocument{graph_id:string;graph_version:string;entrypoints?:string[];nodes:RuleGraphNode[];edges:RuleGraphEdge[];[key:string]:unknown;}
export interface GraphValidationIssue{code:string;message:string;pointer:string;severity:"error"|"warning";}
export interface GraphValidationReport{valid:boolean;issues:GraphValidationIssue[];statistics:{nodes:number;edges:number;rules:number;executableRules:number};}
const record=(v:unknown):v is Record<string,unknown>=>typeof v==="object"&&v!==null&&!Array.isArray(v);
export function parseRuleGraph(value:unknown):RuleGraphDocument{if(!record(value)||typeof value.graph_id!=="string"||typeof value.graph_version!=="string"||!Array.isArray(value.nodes)||!Array.isArray(value.edges))throw new Error("Invalid rule graph");return value as unknown as RuleGraphDocument;}
export function validateRuleGraph(graph:RuleGraphDocument):GraphValidationReport{
 const issues:GraphValidationIssue[]=[];const nodes=new Map<string,RuleGraphNode>();const edgeIds=new Set<string>();const modes=new Set(["deterministic","hybrid","keeper_judgment"]);
 graph.nodes.forEach((node,index)=>{if(!node.id){issues.push({code:"NODE_ID",message:"Missing id",pointer:`/nodes/${index}`,severity:"error"});return;}if(nodes.has(node.id))issues.push({code:"DUPLICATE_NODE",message:node.id,pointer:`/nodes/${index}`,severity:"error"});nodes.set(node.id,node);if(node.execution&&!modes.has(node.execution))issues.push({code:"EXECUTION_MODE",message:node.id,pointer:`/nodes/${index}`,severity:"error"});});
 graph.edges.forEach((edge,index)=>{if(edgeIds.has(edge.id))issues.push({code:"DUPLICATE_EDGE",message:edge.id,pointer:`/edges/${index}`,severity:"error"});edgeIds.add(edge.id);if(!nodes.has(edge.source))issues.push({code:"DANGLING_SOURCE",message:edge.source,pointer:`/edges/${index}`,severity:"error"});if(!nodes.has(edge.target))issues.push({code:"DANGLING_TARGET",message:edge.target,pointer:`/edges/${index}`,severity:"error"});});
 const rules=graph.nodes.filter((n)=>n.kind==="Rule");return{valid:!issues.some((i)=>i.severity==="error"),issues,statistics:{nodes:graph.nodes.length,edges:graph.edges.length,rules:rules.length,executableRules:rules.filter((r)=>r.execution==="deterministic"||r.execution==="hybrid").length}};
}
export interface RandomSource{draw(sides:number,streamId:string):{result:number;receipt:RngReceipt};}
export class SequenceRandomSource implements RandomSource{private index=0;constructor(private readonly results:number[],private readonly ids:IdGenerator){}draw(sides:number,streamId:string){const result=this.results[this.index];if(result===undefined||result<1||result>sides)throw new Error("Invalid injected random result");const drawIndex=this.index++;return{result,receipt:{receiptId:this.ids.next("rng"),streamId,drawIndex,sides,result}};}}
export interface RuleExecutionContext{fictionTime:FictionTime;random:RandomSource;idGenerator:IdGenerator;}
export type RuleExecutor=(request:RuleRequest,context:RuleExecutionContext)=>RuleResolution;
export class RuleExecutorRegistry{private executors=new Map<string,RuleExecutor>();register(id:string,executor:RuleExecutor){if(this.executors.has(id))throw new Error(`Duplicate executor ${id}`);this.executors.set(id,executor);}execute(request:RuleRequest,context:RuleExecutionContext){const executor=this.executors.get(request.ruleId);if(!executor)throw new Error(`No deterministic executor registered for ${request.ruleId}`);return executor(request,context);}}
export interface RulePatch{patchId:string;operation:"ENABLES"|"DISABLES"|"AUGMENTS"|"OVERRIDES";targetRuleId:string;replacementRuleId?:string;layer:string;scope:string;}
export interface EffectiveRuleSet{graph:RuleGraphDocument;enabledRuleIds:Set<string>;disabledRuleIds:Set<string>;hash:string;}
export function compileEffectiveRules(graph:RuleGraphDocument,patches:RulePatch[],hash:string):EffectiveRuleSet{const enabled=new Set(graph.nodes.filter((n)=>n.kind==="Rule"&&n.enabled_by_default!==false).map((n)=>n.id));const disabled=new Set<string>();for(const p of patches){if(p.operation==="DISABLES"){enabled.delete(p.targetRuleId);disabled.add(p.targetRuleId);}else if(p.operation==="ENABLES"){enabled.add(p.targetRuleId);disabled.delete(p.targetRuleId);}else{if(!p.replacementRuleId)throw new Error(`Patch ${p.patchId} requires replacementRuleId`);if(p.operation==="OVERRIDES"){enabled.delete(p.targetRuleId);disabled.add(p.targetRuleId);}enabled.add(p.replacementRuleId);}}return{graph,enabledRuleIds:enabled,disabledRuleIds:disabled,hash};}
export class RuleEngine{constructor(private readonly rules:EffectiveRuleSet,private readonly registry:RuleExecutorRegistry){}resolve(requests:RuleRequest[],context:RuleExecutionContext){return requests.map((request)=>{if(!this.rules.enabledRuleIds.has(request.ruleId))throw new Error(`Rule ${request.ruleId} is disabled`);return this.registry.execute(request,context);});}}
export type SuccessLevel="critical"|"extreme"|"hard"|"regular"|"failure"|"fumble";
export function classifyPercentile(roll:number,ability:number):SuccessLevel{if(roll===1)return"critical";if((ability<50&&roll>=96)||roll===100)return"fumble";if(roll<=Math.floor(ability/5))return"extreme";if(roll<=Math.floor(ability/2))return"hard";if(roll<=ability)return"regular";return"failure";}
const rank:Record<SuccessLevel,number>={fumble:0,failure:1,regular:2,hard:3,extreme:4,critical:5};
export function percentileExecutor(request:RuleRequest,context:RuleExecutionContext):RuleResolution{const ability=request.inputs.ability;if(typeof ability!=="number")throw new Error("ability must be numeric");const difficulty=request.proposedDifficulty??"regular";const supplied=request.inputs.roll;const receipts:RngReceipt[]=[];let roll:number;if(typeof supplied==="number")roll=supplied;else{const drawn=context.random.draw(100,`rule:${request.ruleId}:${request.requestId}`);roll=drawn.result;receipts.push(drawn.receipt);}const level=classifyPercentile(roll,ability);const succeeded=rank[level]>=rank[difficulty];const event:DomainEvent={eventId:context.idGenerator.next("evt"),eventType:"PercentileCheckResolved",aggregateId:request.actorId,payload:{requestId:request.requestId,roll,ability,difficulty,successLevel:level,succeeded},visibility:{scope:"party"},fictionTime:context.fictionTime,causedBy:[request.requestId],ruleRefs:[request.ruleId],sourceRefs:[]};return{requestId:request.requestId,ruleId:request.ruleId,outcome:succeeded?"success":"failure",data:{roll,ability,difficulty,successLevel:level,succeeded},events:[event],rngReceipts:receipts};}
export function createCoreRegistry(){const registry=new RuleExecutorRegistry();registry.register("rule:resolution.roll_d100",percentileExecutor);registry.register("coc7.skill.check",percentileExecutor);return registry;}
