/** Emit host-loadable JavaScript with the same pinned build tool as the Pi package. */
import { build } from 'esbuild';
import { dirname, resolve,relative } from 'node:path';
import {readdirSync,readFileSync,writeFileSync,existsSync,mkdirSync,copyFileSync} from 'node:fs';
import ts from 'typescript';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
// Preserve the engine-owned clock convention without a handwritten runtime registry.
const kernelRoot=resolve(root,'kernel-ts'),engines=[];
for(const entry of readdirSync(kernelRoot,{recursive:true,withFileTypes:true})){
  if(!entry.isFile()||!entry.name.endsWith('.ts')||entry.name.endsWith('.d.ts'))continue;
  const path=resolve(entry.parentPath??entry.path,entry.name),source=ts.createSourceFile(path,readFileSync(path,'utf8'),ts.ScriptTarget.Latest,true);
  const exported=new Set();let declaresPaths=false;
  for(const statement of source.statements){
    if(statement.modifiers?.some(modifier=>modifier.kind===ts.SyntaxKind.ExportKeyword)){
      if(ts.isVariableStatement(statement))for(const declaration of statement.declarationList.declarations)if(ts.isIdentifier(declaration.name)){exported.add(declaration.name.text);if(declaration.name.text==='CLOCK_SAVE_PATHS')declaresPaths=true;}
      if(ts.isFunctionDeclaration(statement)&&statement.name)exported.add(statement.name.text);
    }
    if(ts.isExportDeclaration(statement)&&statement.exportClause&&ts.isNamedExports(statement.exportClause))for(const value of statement.exportClause.elements)exported.add(value.name.text);
  }
  if(declaresPaths){if(!exported.has('rebaseClock'))throw new Error(`${path} declares clock files without rebaseClock`);engines.push(relative(kernelRoot,path).split('\\').join('/'));}
}
engines.sort();
const generated=`/** Generated by build-runtime.mjs from engine-owned clock declarations. */\nimport type {ClockEngine} from './worldline/reset.js';\n`+engines.map((path,index)=>`import * as engine${index} from './${path.replace(/\.ts$/,'.js')}';`).join('\n')+`\nexport const clockEngines: readonly ClockEngine[] = Object.freeze([\n`+engines.map((path,index)=>`  {name:${JSON.stringify(path)},paths:engine${index}.CLOCK_SAVE_PATHS,rebase:engine${index}.rebaseClock},`).join('\n')+'\n]);\n';
writeFileSync(resolve(kernelRoot,'clock-engines.generated.ts'),generated);
const manifest=JSON.parse(readFileSync(resolve(root,'pipicoc/runtime-dependencies.json'),'utf8'));
const entryPoints={};
for(const entry of manifest.requiredEntries){
  if(typeof entry!=='string'||entry.includes('..')||!entry.endsWith('.mjs'))throw new Error('Invalid compiled runtime entry');
  const stem=entry.startsWith('build/kernel/')?entry.replace(/^build\/kernel\//,'kernel-ts/'):
    entry.startsWith('build/host/runtime/')?entry.replace(/^build\/host\/runtime\//,'Electron/resources/runtime/'):
    /^build\/(runtime|pipicoc|extensions)\//.test(entry)?entry.slice(6):null;
  if(!stem)throw new Error(`Unknown runtime entry root: ${entry}`);
  const bare=entry==='build/extensions/module/source.mjs'?'extensions/module/source-cli':stem.slice(0,-4),source=['.ts','.mjs','.js'].map(extension=>bare+extension).find(path=>existsSync(resolve(root,path)));
  if(!source)throw new Error(`Missing source for required runtime entry: ${entry}`);
  entryPoints[entry.slice(6,-4)]=source;
}
await build({
  absWorkingDir: root,
  entryPoints,
  outdir: resolve(root, 'build'),
  outExtension: {'.js': '.mjs'},
  bundle: true,
  packages: 'external',
  platform: 'node',
  format: 'esm',
  target: 'node22',
  sourcemap: true,
  logLevel: 'warning',
});
// Assets used next to emitted entrypoints have the same layout in source and packaged runs.
const copyAssets=(source,destination)=>{
  for(const entry of readdirSync(source,{withFileTypes:true})){
    const from=resolve(source,entry.name),to=resolve(destination,entry.name);
    if(entry.isDirectory()){copyAssets(from,to);continue;}
    if(!entry.isFile()||entry.name.endsWith('.ts')||entry.name.endsWith('.map'))continue;
    mkdirSync(dirname(to),{recursive:true});copyFileSync(from,to);
  }
};
copyAssets(resolve(root,'Electron/resources/runtime'),resolve(root,'build/host/runtime'));
// Bundled auth-provider extensions: the auth helper (pi-auth-helper.mjs registerBundledAuthProviders)
// scans build/host/runtime/extensions/<name>/agent/dist/provider.js to register extension
// auth.providers into the external auth runtime; without this tree the model manager never
// sees extension providers (grok-build was invisible). Layout is agent/ -> agent/dist/.
copyAssets(resolve(root,'extensions/grok-build-oauth/agent'),resolve(root,'build/host/runtime/extensions/grok-build-oauth/agent/dist'));
for(const file of manifest.uiFiles){mkdirSync(resolve(root,'build/pipicoc'),{recursive:true});copyFileSync(resolve(root,'pipicoc',file),resolve(root,'build/pipicoc',file));}
copyAssets(resolve(root,'pipicoc/assets'),resolve(root,'build/pipicoc/assets'));
