#!/usr/bin/env python3
from __future__ import annotations

from copy import deepcopy
from typing import Any


DEFAULT_PLAY_LANGUAGE = "zh-Hans"

BASE_REPORT_LABELS = {
    "roll_sentence": "- {skill}: {actor} rolled {roll} vs {target} -> {outcome}",
    "difficulty": "Difficulty",
    "goal": "Goal",
    "difficulty_rationale": "Difficulty Rationale",
    "failure_consequence": "Failure Consequence",
    "pushed_roll": "Pushed Roll",
    "push_justification": "Push Justification",
    "foreshadowed_failure": "Foreshadowed Failure",
    "skill_check_earned": "Skill Check Earned",
    "san_loss": "SAN Loss",
    "yes": "yes",
    "no": "no",
    "localized_terms_summary": "{count} entries (see Localization Appendix)",
    "feedback_line": "- {category} {score}/5: {voice}: \"{text}\"",
    "feedback_voice_default": "Player feedback",
    "feedback_voice_profile": "{profile} feedback",
}

BASE_EMPTY_REPORT_LINES = {
    "combat_summary": "- No combat summary recorded.",
    "chase_summary": "- No chase summary recorded.",
    "chase_tracker": "- No chase tracker recorded.",
    "sanity_summary": "- No sanity summary recorded.",
}

BASE_SPEAKER_LABELS = {
    "keeper": "KP",
    "player": "Player",
    "system": "system",
}

BASE_TRANSCRIPT_LABELS = {
    "turn_format": "Turn {turn}",
    "mode": "Mode",
    "intent": "Intent",
    "ruling": "Ruling",
}

BASE_TRANSCRIPT_MODE_LABELS = {
    "play": "play",
    "roll": "roll",
    "meta": "meta",
}

BASE_REPORT_HEADING_LABELS = {
    "Battle Report": "Battle Report",
    "Run Setup": "Run Setup",
    "Module": "Module",
    "Investigator Creation": "Investigator Creation",
    "Character Dossier": "Character Dossier",
    "Investigator Chronicle": "Investigator Chronicle",
    "Scene-by-Scene Replay": "Scene-by-Scene Replay",
    "Actual Play Replay": "Actual Play Replay",
    "Session Transcript": "Session Transcript",
    "Major Player Decisions": "Major Player Decisions",
    "Rules & Rolls Recap": "Rules & Rolls Recap",
    "Mechanical Log": "Mechanical Log",
    "Important Rolls": "Important Rolls",
    "State Changes": "State Changes",
    "Combat Summary": "Combat Summary",
    "Chase Summary": "Chase Summary",
    "Chase Tracker": "Chase Tracker",
    "Sanity Summary": "Sanity Summary",
    "Clues Found": "Clues Found",
    "Session Ending": "Session Ending",
    "Story Recap": "Story Recap",
    "Player Feedback On KP": "Player Feedback On KP",
    "Localization Appendix": "Localization Appendix",
}

BASE_REPORT_FIELD_LABELS = {
    "Run ID": "Run ID",
    "Campaign": "Campaign",
    "Era": "Era",
    "Dice Mode": "Dice Mode",
    "Spoiler Policy": "Spoiler Policy",
    "Play Language": "Play Language",
    "Language Profile": "Language Profile",
    "Localized Terms": "Localized Terms",
    "Player Profile": "Player Profile",
    "Scenario": "Scenario",
    "Scenario ID": "Scenario ID",
    "Source": "Source",
    "Opening Scene": "Opening Scene",
}

BASE_REPORT_VALUE_LABELS = {
    "codex": "codex",
    "warn_before_reveal": "warn_before_reveal",
    "Simplified Chinese": "Simplified Chinese",
    "English": "English",
    "Japanese": "Japanese",
    "careful_investigator": "careful_investigator",
    "reckless_investigator": "reckless_investigator",
    "skeptical_rules_lawyer": "skeptical_rules_lawyer",
    "multi_profile_matrix": "multi_profile_matrix",
}

BASE_CHARACTER_DOSSIER_LABELS = {
    "Player": "Player",
    "Occupation": "Occupation",
    "Era": "Era",
    "Characteristics": "Characteristics",
    "Derived": "Derived",
    "damage_bonus": "DB",
    "build": "Build",
    "Skills": "Skills",
    "Backstory": "Backstory",
    "Description": "Description",
    "Ideology/Beliefs": "Ideology/Beliefs",
    "Significant People": "Significant People",
    "Meaningful Locations": "Meaningful Locations",
    "Treasured Possessions": "Treasured Possessions",
    "Traits": "Traits",
    "Injuries & Scars": "Injuries & Scars",
    "Phobias & Manias": "Phobias & Manias",
}

BASE_CREATION_LABELS = {
    "Rulebook Source": "Rulebook Source",
    "Method": "Method",
    "Rulebook Steps": "Rulebook Steps",
    "Characteristics": "Characteristics",
    "Age": "Age",
    "Derived Attributes": "Derived Attributes",
    "Occupation": "Occupation",
    "Occupation Skill Points": "Occupation Skill Points",
    "Personal Interest Skill Points": "Personal Interest Skill Points",
    "Credit Rating": "Credit Rating",
    "Rulebook Occupation Range": "rulebook occupation range",
    "Skill Allocation": "Skill Allocation",
    "Personal Interest": "Personal Interest",
    "Unallocated": "Unallocated",
    "Backstory": "Backstory",
    "Equipment": "Equipment",
    "Notes": "Notes",
    "standard_rulebook_chapter_3": "standard rulebook Chapter 3",
    "Call of Cthulhu Keeper Rulebook Chapter 3": "Call of Cthulhu Keeper Rulebook Chapter 3",
}

BASE_CHRONICLE_LABELS = {
    "History": "History",
    "Development": "Development",
    "Inventory History": "Inventory History",
    "Final HP": "Final HP",
    "Final SAN": "Final SAN",
    "Notable Events": "Notable Events",
    "Unresolved Threads": "Unresolved Threads",
    "Development Entry": "Development Entry",
    "Development Phase Summary": "Development Phase Summary",
    "Status": "Status",
    "Skill Checks Earned": "Skill Checks Earned",
    "Rewards": "Rewards",
    "Permanent Changes": "Permanent Changes",
    "Carryover Notes": "Carryover Notes",
    "Items": "Items",
    "Cash": "Cash",
    "Notes": "Notes",
    "pending_player_rolls": "pending_player_rolls",
}

BASE_FEEDBACK_LABELS = {
    "kp_clarity": "kp_clarity",
    "rules_helpfulness": "rules_helpfulness",
    "immersion": "immersion",
    "pacing": "pacing",
    "fairness": "fairness",
    "agency": "agency",
    "meta_quality": "meta_quality",
    "spoiler_safety": "spoiler_safety",
    "module_fidelity": "module_fidelity",
    "combat_readability": "combat_readability",
    "chase_readability": "chase_readability",
}

BASE_CHASE_TRACKER_LABELS = {
    "Chase ID": "Chase ID",
    "Status": "Status",
    "Round": "Round",
    "DEX order": "DEX order",
    "Participants": "Participants",
    "Location Chain": "Location Chain",
    "Rounds": "Rounds",
    "Outcome": "Outcome",
    "movement_actions": "actions",
    "position": "position",
    "round_format": "Round {round}",
    "start": "start",
    "clear": "clear",
    "hazard": "hazard",
    "barrier": "barrier",
    "escape": "escape",
    "quarry": "quarry",
    "pursuer": "pursuer",
    "resolved": "resolved",
}

LANGUAGE_PROFILES: dict[str, dict[str, Any]] = {
    "zh-Hans": {
        "language": "zh-Hans",
        "display_name": "Simplified Chinese",
        "output_instruction": "Use Simplified Chinese for player-visible narration, table dialogue, recaps, and reports.",
        "name_policy": "Foreign names should use Chinese transliterations or conventional translated names.",
        "term_policy": "Use localized_terms.zh-Hans for people, places, factions, handouts, campaign titles, scenario titles, player-visible module source labels, player-visible skill display names, and special terms.",
        "report_labels": {
            "roll_sentence": "- {skill}：{actor}掷出 {roll} / {target}，结果{outcome}。",
            "difficulty": "难度",
            "goal": "目的",
            "difficulty_rationale": "难度说明",
            "failure_consequence": "失败后果",
            "pushed_roll": "推骰",
            "push_justification": "推骰理由",
            "foreshadowed_failure": "预告失败后果",
            "skill_check_earned": "成长标记",
            "san_loss": "SAN 损失",
            "yes": "是",
            "no": "否",
            "localized_terms_summary": "{count} 条（见本地化附录）",
            "feedback_line": "- {category} {score}/5：{voice}：“{text}”",
            "feedback_voice_default": "玩家反馈",
            "feedback_voice_profile": "{profile}反馈",
        },
        "report_heading_labels": {
            "Battle Report": "跑团战报",
            "Run Setup": "运行设置",
            "Module": "模组",
            "Investigator Creation": "角色创建记录",
            "Character Dossier": "角色档案",
            "Investigator Chronicle": "调查员经历",
            "Scene-by-Scene Replay": "逐场景回放",
            "Actual Play Replay": "实际跑团回放",
            "Session Transcript": "会话记录",
            "Major Player Decisions": "玩家关键决定",
            "Rules & Rolls Recap": "规则与掷骰回顾",
            "Mechanical Log": "机制日志",
            "Important Rolls": "重要掷骰",
            "State Changes": "状态变化",
            "Combat Summary": "战斗摘要",
            "Chase Summary": "追逐摘要",
            "Chase Tracker": "追逐追踪器",
            "Sanity Summary": "理智摘要",
            "Clues Found": "已发现线索",
            "Session Ending": "本次结局",
            "Story Recap": "剧情回顾",
            "Player Feedback On KP": "玩家对 KP 的反馈",
            "Localization Appendix": "本地化附录",
        },
        "report_field_labels": {
            "Run ID": "运行编号",
            "Campaign": "战役",
            "Era": "年代",
            "Dice Mode": "骰子模式",
            "Spoiler Policy": "剧透策略",
            "Play Language": "游玩语言",
            "Language Profile": "语言配置",
            "Localized Terms": "本地化术语",
            "Player Profile": "玩家画像",
            "Scenario": "模组",
            "Scenario ID": "模组 ID",
            "Source": "来源",
            "Opening Scene": "开场场景",
        },
        "report_value_labels": {
            "codex": "Codex 掷骰",
            "warn_before_reveal": "剧透前警告",
            "Simplified Chinese": "简体中文",
            "English": "英语",
            "Japanese": "日语",
            "careful_investigator": "谨慎调查员",
            "reckless_investigator": "鲁莽调查员",
            "skeptical_rules_lawyer": "规则质疑玩家",
            "multi_profile_matrix": "多玩家画像矩阵",
        },
        "character_dossier_labels": {
            "Player": "玩家",
            "Occupation": "职业",
            "Era": "年代",
            "Characteristics": "属性",
            "Derived": "衍生值",
            "damage_bonus": "DB",
            "build": "体格",
            "Skills": "技能",
            "Backstory": "背景",
            "Description": "描述",
            "Ideology/Beliefs": "信念/理念",
            "Significant People": "重要之人",
            "Meaningful Locations": "重要地点",
            "Treasured Possessions": "珍贵物品",
            "Traits": "特质",
            "Injuries & Scars": "伤疤与伤势",
            "Phobias & Manias": "恐惧与躁狂",
        },
        "creation_labels": {
            "Rulebook Source": "规则书来源",
            "Method": "创建方法",
            "Rulebook Steps": "规则书步骤",
            "Characteristics": "生成属性",
            "Age": "年龄",
            "Derived Attributes": "衍生值",
            "Occupation": "职业",
            "Occupation Skill Points": "职业技能点",
            "Personal Interest Skill Points": "个人兴趣技能点",
            "Credit Rating": "信用评级",
            "Rulebook Occupation Range": "规则书职业范围",
            "Skill Allocation": "技能分配",
            "Personal Interest": "个人兴趣",
            "Unallocated": "未分配",
            "Backstory": "背景",
            "Equipment": "装备",
            "Notes": "备注",
            "standard_rulebook_chapter_3": "规则书第 3 章标准创建",
            "Call of Cthulhu Keeper Rulebook Chapter 3": "《克苏鲁的呼唤守秘人规则书》第 3 章",
        },
        "chronicle_labels": {
            "History": "经历",
            "Development": "成长",
            "Inventory History": "物品经历",
            "Final HP": "最终 HP",
            "Final SAN": "最终 SAN",
            "Notable Events": "重要事件",
            "Unresolved Threads": "未解线索",
            "Development Entry": "成长条目",
            "Development Phase Summary": "成长阶段摘要",
            "Status": "状态",
            "Skill Checks Earned": "获得成长标记",
            "Rewards": "奖励",
            "Permanent Changes": "永久变化",
            "Carryover Notes": "继承备注",
            "Items": "物品",
            "Cash": "现金",
            "Notes": "备注",
            "pending_player_rolls": "等待玩家成长检定",
        },
        "feedback_labels": {
            "kp_clarity": "KP 清晰度",
            "rules_helpfulness": "规则帮助度",
            "immersion": "沉浸感",
            "pacing": "节奏",
            "fairness": "公平性",
            "agency": "自主性",
            "meta_quality": "超游质量",
            "spoiler_safety": "剧透安全",
            "module_fidelity": "模组忠实度",
            "combat_readability": "战斗可读性",
            "chase_readability": "追逐可读性",
        },
        "chase_tracker_labels": {
            "Chase ID": "追逐 ID",
            "Status": "状态",
            "Round": "当前轮数",
            "DEX order": "DEX 顺序",
            "Participants": "参与者",
            "Location Chain": "位置链",
            "Rounds": "轮次",
            "Outcome": "结果",
            "movement_actions": "移动行动",
            "position": "位置",
            "round_format": "第 {round} 轮",
            "start": "起点",
            "clear": "通路",
            "hazard": "危险点",
            "barrier": "障碍",
            "escape": "逃脱点",
            "quarry": "被追者",
            "pursuer": "追赶者",
            "resolved": "已解决",
        },
        "empty_report_lines": {
            "combat_summary": "- 本轮没有触发战斗场面。",
            "chase_summary": "- 本轮没有触发追逐场面。",
            "chase_tracker": "- 本轮没有追逐状态需要追踪。",
            "sanity_summary": "- 本轮没有触发理智检定或疯狂事件。",
        },
        "speaker_labels": {
            "keeper": "KP",
            "player": "玩家",
            "system": "系统",
        },
        "transcript_labels": {
            "turn_format": "第 {turn} 轮",
            "mode": "模式",
            "intent": "意图",
            "ruling": "裁定",
        },
        "transcript_mode_labels": {
            "play": "游玩",
            "roll": "掷骰",
            "meta": "超游",
        },
        "outcome_labels": {
            "critical": "大成功",
            "extreme_success": "极难成功",
            "hard_success": "困难成功",
            "regular_success": "普通成功",
            "success": "成功",
            "failure": "失败",
            "fumble": "大失败",
        },
        "difficulty_labels": {
            "regular": "普通",
            "hard": "困难",
            "extreme": "极难",
            "opposed": "对抗",
            "combined": "联合",
            "sanity": "理智",
        },
        "raw_payload_fallback": False,
    },
    "en-US": {
        "language": "en-US",
        "display_name": "English",
        "output_instruction": "Use English for player-visible narration, table dialogue, recaps, and reports.",
        "name_policy": "Use customary English names and established scenario terminology.",
        "term_policy": "Use localized_terms.en-US for player-visible aliases and skill display names when the source term needs an English table form.",
        "report_labels": BASE_REPORT_LABELS,
        "report_heading_labels": BASE_REPORT_HEADING_LABELS,
        "report_field_labels": BASE_REPORT_FIELD_LABELS,
        "report_value_labels": BASE_REPORT_VALUE_LABELS,
        "character_dossier_labels": BASE_CHARACTER_DOSSIER_LABELS,
        "creation_labels": BASE_CREATION_LABELS,
        "chronicle_labels": BASE_CHRONICLE_LABELS,
        "feedback_labels": BASE_FEEDBACK_LABELS,
        "chase_tracker_labels": BASE_CHASE_TRACKER_LABELS,
        "empty_report_lines": BASE_EMPTY_REPORT_LINES,
        "speaker_labels": BASE_SPEAKER_LABELS,
        "transcript_labels": BASE_TRANSCRIPT_LABELS,
        "transcript_mode_labels": BASE_TRANSCRIPT_MODE_LABELS,
        "outcome_labels": {},
        "difficulty_labels": {},
        "raw_payload_fallback": True,
    },
    "ja-JP": {
        "language": "ja-JP",
        "display_name": "Japanese",
        "output_instruction": "Use Japanese for player-visible narration, table dialogue, recaps, and reports.",
        "name_policy": "Foreign names should use customary Japanese katakana forms or established translated names.",
        "term_policy": "Use localized_terms.ja-JP for people, places, factions, handouts, campaign titles, scenario titles, player-visible module source labels, player-visible skill display names, and special terms.",
        "report_labels": {
            "roll_sentence": "- {skill}：{actor}は {roll} / {target} を振り、結果は{outcome}。",
            "difficulty": "難易度",
            "goal": "目的",
            "difficulty_rationale": "難易度の理由",
            "failure_consequence": "失敗時の結果",
            "pushed_roll": "プッシュロール",
            "push_justification": "プッシュ理由",
            "foreshadowed_failure": "失敗予告",
            "skill_check_earned": "成長チェック",
            "san_loss": "SAN 喪失",
            "yes": "はい",
            "no": "いいえ",
            "localized_terms_summary": "{count} 件（ローカライズ付録を参照）",
            "feedback_line": "- {category} {score}/5：{voice}：「{text}」",
            "feedback_voice_default": "プレイヤー感想",
            "feedback_voice_profile": "{profile}の感想",
        },
        "report_heading_labels": {
            "Battle Report": "プレイ報告",
            "Run Setup": "実行設定",
            "Module": "シナリオ",
            "Investigator Creation": "探索者作成記録",
            "Character Dossier": "キャラクター記録",
            "Investigator Chronicle": "探索者履歴",
            "Scene-by-Scene Replay": "シーン別リプレイ",
            "Actual Play Replay": "実プレイリプレイ",
            "Session Transcript": "セッション記録",
            "Major Player Decisions": "主なプレイヤー判断",
            "Rules & Rolls Recap": "ルールとロールの要約",
            "Mechanical Log": "メカニクス記録",
            "Important Rolls": "重要なロール",
            "State Changes": "状態変化",
            "Combat Summary": "戦闘要約",
            "Chase Summary": "チェイス要約",
            "Chase Tracker": "チェイス追跡",
            "Sanity Summary": "正気度要約",
            "Clues Found": "発見した手がかり",
            "Session Ending": "セッション終了",
            "Story Recap": "物語の要約",
            "Player Feedback On KP": "KP へのプレイヤーフィードバック",
            "Localization Appendix": "ローカライズ付録",
        },
        "report_field_labels": {
            "Run ID": "実行 ID",
            "Campaign": "キャンペーン",
            "Era": "時代",
            "Dice Mode": "ダイス方式",
            "Spoiler Policy": "ネタバレ方針",
            "Play Language": "プレイ言語",
            "Language Profile": "言語プロファイル",
            "Localized Terms": "ローカライズ用語",
            "Player Profile": "プレイヤープロファイル",
            "Scenario": "シナリオ",
            "Scenario ID": "シナリオ ID",
            "Source": "出典",
            "Opening Scene": "導入シーン",
        },
        "report_value_labels": {
            "codex": "Codex ダイス",
            "warn_before_reveal": "ネタバレ前に警告",
            "Simplified Chinese": "簡体字中国語",
            "English": "英語",
            "Japanese": "日本語",
            "careful_investigator": "慎重な探索者",
            "reckless_investigator": "無謀な探索者",
            "skeptical_rules_lawyer": "ルール確認型プレイヤー",
            "multi_profile_matrix": "複数プロファイル行列",
        },
        "character_dossier_labels": {
            "Player": "プレイヤー",
            "Occupation": "職業",
            "Era": "時代",
            "Characteristics": "能力値",
            "Derived": "派生値",
            "damage_bonus": "DB",
            "build": "ビルド",
            "Skills": "技能",
            "Backstory": "バックストーリー",
            "Description": "描写",
            "Ideology/Beliefs": "思想/信念",
            "Significant People": "重要人物",
            "Meaningful Locations": "重要な場所",
            "Treasured Possessions": "大切な所持品",
            "Traits": "特徴",
            "Injuries & Scars": "負傷と傷跡",
            "Phobias & Manias": "恐怖症と躁症",
        },
        "creation_labels": {
            "Rulebook Source": "ルールブック出典",
            "Method": "作成方法",
            "Rulebook Steps": "ルールブック手順",
            "Characteristics": "能力値生成",
            "Age": "年齢",
            "Derived Attributes": "派生値",
            "Occupation": "職業",
            "Occupation Skill Points": "職業技能ポイント",
            "Personal Interest Skill Points": "個人的興味技能ポイント",
            "Credit Rating": "信用",
            "Rulebook Occupation Range": "ルールブック職業範囲",
            "Skill Allocation": "技能配分",
            "Personal Interest": "個人的興味",
            "Unallocated": "未配分",
            "Backstory": "背景",
            "Equipment": "装備",
            "Notes": "メモ",
            "standard_rulebook_chapter_3": "ルールブック第3章標準作成",
            "Call of Cthulhu Keeper Rulebook Chapter 3": "Call of Cthulhu Keeper Rulebook 第3章",
        },
        "chronicle_labels": {
            "History": "履歴",
            "Development": "成長",
            "Inventory History": "所持品履歴",
            "Final HP": "最終 HP",
            "Final SAN": "最終 SAN",
            "Notable Events": "主な出来事",
            "Unresolved Threads": "未解決の糸口",
            "Development Entry": "成長記録",
            "Development Phase Summary": "成長フェイズ要約",
            "Status": "状態",
            "Skill Checks Earned": "獲得した成長チェック",
            "Rewards": "報酬",
            "Permanent Changes": "恒久的な変化",
            "Carryover Notes": "引き継ぎメモ",
            "Items": "アイテム",
            "Cash": "現金",
            "Notes": "メモ",
            "pending_player_rolls": "プレイヤーの成長ロール待ち",
        },
        "feedback_labels": {
            "kp_clarity": "KP の明瞭さ",
            "rules_helpfulness": "ルール説明の有用性",
            "immersion": "没入感",
            "pacing": "進行速度",
            "fairness": "公平性",
            "agency": "主体性",
            "meta_quality": "メタ相談の質",
            "spoiler_safety": "ネタバレ安全性",
            "module_fidelity": "モジュール忠実度",
            "combat_readability": "戦闘の読みやすさ",
            "chase_readability": "チェイスの読みやすさ",
        },
        "chase_tracker_labels": {
            "Chase ID": "チェイス ID",
            "Status": "状態",
            "Round": "現在ラウンド",
            "DEX order": "DEX 順",
            "Participants": "参加者",
            "Location Chain": "ロケーション列",
            "Rounds": "ラウンド",
            "Outcome": "結果",
            "movement_actions": "移動アクション",
            "position": "位置",
            "round_format": "第 {round} ラウンド",
            "start": "開始地点",
            "clear": "通常地点",
            "hazard": "危険",
            "barrier": "障害",
            "escape": "逃走地点",
            "quarry": "逃走側",
            "pursuer": "追跡側",
            "resolved": "解決済み",
        },
        "empty_report_lines": {
            "combat_summary": "- 今回は戦闘場面は発生していない。",
            "chase_summary": "- 今回はチェイス場面は発生していない。",
            "chase_tracker": "- 今回は追跡するチェイス状態はない。",
            "sanity_summary": "- 今回は正気度判定や狂気イベントは発生していない。",
        },
        "speaker_labels": {
            "keeper": "KP",
            "player": "プレイヤー",
            "system": "システム",
        },
        "transcript_labels": {
            "turn_format": "第 {turn} ターン",
            "mode": "モード",
            "intent": "意図",
            "ruling": "裁定",
        },
        "transcript_mode_labels": {
            "play": "プレイ",
            "roll": "ロール",
            "meta": "メタ",
        },
        "outcome_labels": {
            "critical": "クリティカル",
            "extreme_success": "イクストリーム成功",
            "hard_success": "ハード成功",
            "regular_success": "レギュラー成功",
            "success": "成功",
            "failure": "失敗",
            "fumble": "ファンブル",
        },
        "difficulty_labels": {
            "regular": "レギュラー",
            "hard": "ハード",
            "extreme": "イクストリーム",
            "opposed": "対抗",
            "combined": "複合",
            "sanity": "正気度",
        },
        "raw_payload_fallback": True,
    },
}


def language_profile(play_language: str | None = None) -> dict[str, Any]:
    language = play_language or DEFAULT_PLAY_LANGUAGE
    if language in LANGUAGE_PROFILES:
        return deepcopy(LANGUAGE_PROFILES[language])
    profile = deepcopy(LANGUAGE_PROFILES["en-US"])
    profile.update({
        "language": language,
        "display_name": language,
        "output_instruction": f"Use {language} for player-visible narration, table dialogue, recaps, and reports.",
        "name_policy": f"Use customary {language} forms for names and setting terms when available.",
        "term_policy": f"Use localized_terms.{language} for player-visible people, places, factions, handouts, campaign titles, scenario titles, player-visible module source labels, player-visible skill display names, and special terms.",
    })
    profile["empty_report_lines"] = BASE_EMPTY_REPORT_LINES
    profile["speaker_labels"] = BASE_SPEAKER_LABELS
    profile["transcript_mode_labels"] = BASE_TRANSCRIPT_MODE_LABELS
    profile["report_heading_labels"] = BASE_REPORT_HEADING_LABELS
    profile["report_field_labels"] = BASE_REPORT_FIELD_LABELS
    profile["report_value_labels"] = BASE_REPORT_VALUE_LABELS
    profile["character_dossier_labels"] = BASE_CHARACTER_DOSSIER_LABELS
    profile["creation_labels"] = BASE_CREATION_LABELS
    profile["chronicle_labels"] = BASE_CHRONICLE_LABELS
    profile["feedback_labels"] = BASE_FEEDBACK_LABELS
    profile["chase_tracker_labels"] = BASE_CHASE_TRACKER_LABELS
    return profile
