#!/usr/bin/env python3
from __future__ import annotations

from copy import deepcopy
from typing import Any


DEFAULT_PLAY_LANGUAGE = "zh-Hans"

BASE_REPORT_LABELS = {
    "roll_sentence": "- {skill}: {actor} rolled {roll} vs {target} -> {outcome}",
    "difficulty": "Difficulty",
    "goal": "Goal",
    "difficulty_rationale": "Difficulty Rationale",
    "failure_consequence": "Failure Consequence",
    "pushed_roll": "Pushed Roll",
    "push_justification": "Push Justification",
    "foreshadowed_failure": "Foreshadowed Failure",
    "skill_check_earned": "Skill Check Earned",
    "san_loss": "SAN Loss",
    "yes": "yes",
    "no": "no",
}

BASE_EMPTY_REPORT_LINES = {
    "combat_summary": "- No combat summary recorded.",
    "chase_summary": "- No chase summary recorded.",
    "chase_tracker": "- No chase tracker recorded.",
    "sanity_summary": "- No sanity summary recorded.",
}

BASE_SPEAKER_LABELS = {
    "keeper": "KP",
    "player": "Player",
    "system": "system",
}

BASE_REPORT_HEADING_LABELS = {
    "Battle Report": "Battle Report",
    "Run Setup": "Run Setup",
    "Module": "Module",
    "Character Dossier": "Character Dossier",
    "Investigator Chronicle": "Investigator Chronicle",
    "Scene-by-Scene Replay": "Scene-by-Scene Replay",
    "Actual Play Replay": "Actual Play Replay",
    "Session Transcript": "Session Transcript",
    "Major Player Decisions": "Major Player Decisions",
    "Rules & Rolls Recap": "Rules & Rolls Recap",
    "Mechanical Log": "Mechanical Log",
    "Important Rolls": "Important Rolls",
    "State Changes": "State Changes",
    "Combat Summary": "Combat Summary",
    "Chase Summary": "Chase Summary",
    "Chase Tracker": "Chase Tracker",
    "Sanity Summary": "Sanity Summary",
    "Clues Found": "Clues Found",
    "Session Ending": "Session Ending",
    "Story Recap": "Story Recap",
    "Player Feedback On KP": "Player Feedback On KP",
    "Localization Appendix": "Localization Appendix",
}

BASE_REPORT_FIELD_LABELS = {
    "Run ID": "Run ID",
    "Campaign": "Campaign",
    "Era": "Era",
    "Dice Mode": "Dice Mode",
    "Spoiler Policy": "Spoiler Policy",
    "Play Language": "Play Language",
    "Language Profile": "Language Profile",
    "Localized Terms": "Localized Terms",
    "Player Profile": "Player Profile",
    "Scenario": "Scenario",
    "Scenario ID": "Scenario ID",
    "Source": "Source",
    "Opening Scene": "Opening Scene",
}

LANGUAGE_PROFILES: dict[str, dict[str, Any]] = {
    "zh-Hans": {
        "language": "zh-Hans",
        "display_name": "Simplified Chinese",
        "output_instruction": "Use Simplified Chinese for player-visible narration, table dialogue, recaps, and reports.",
        "name_policy": "Foreign names should use Chinese transliterations or conventional translated names.",
        "term_policy": "Use localized_terms.zh-Hans for people, places, factions, handouts, scenario titles, and special terms.",
        "report_labels": {
            "roll_sentence": "- {skill}：{actor}掷出 {roll} / {target}，结果{outcome}。",
            "difficulty": "难度",
            "goal": "目的",
            "difficulty_rationale": "难度说明",
            "failure_consequence": "失败后果",
            "pushed_roll": "推骰",
            "push_justification": "推骰理由",
            "foreshadowed_failure": "预告失败后果",
            "skill_check_earned": "成长标记",
            "san_loss": "SAN 损失",
            "yes": "yes",
            "no": "no",
        },
        "report_heading_labels": {
            "Battle Report": "跑团战报",
            "Run Setup": "运行设置",
            "Module": "模组",
            "Character Dossier": "角色档案",
            "Investigator Chronicle": "调查员经历",
            "Scene-by-Scene Replay": "逐场景回放",
            "Actual Play Replay": "实际跑团回放",
            "Session Transcript": "会话记录",
            "Major Player Decisions": "玩家关键决定",
            "Rules & Rolls Recap": "规则与掷骰回顾",
            "Mechanical Log": "机制日志",
            "Important Rolls": "重要掷骰",
            "State Changes": "状态变化",
            "Combat Summary": "战斗摘要",
            "Chase Summary": "追逐摘要",
            "Chase Tracker": "追逐追踪器",
            "Sanity Summary": "理智摘要",
            "Clues Found": "已发现线索",
            "Session Ending": "本次结局",
            "Story Recap": "剧情回顾",
            "Player Feedback On KP": "玩家对 KP 的反馈",
            "Localization Appendix": "本地化附录",
        },
        "report_field_labels": {
            "Run ID": "运行编号",
            "Campaign": "战役",
            "Era": "年代",
            "Dice Mode": "骰子模式",
            "Spoiler Policy": "剧透策略",
            "Play Language": "游玩语言",
            "Language Profile": "语言配置",
            "Localized Terms": "本地化术语",
            "Player Profile": "玩家画像",
            "Scenario": "模组",
            "Scenario ID": "模组 ID",
            "Source": "来源",
            "Opening Scene": "开场场景",
        },
        "empty_report_lines": {
            "combat_summary": "- 本轮没有触发战斗场面。",
            "chase_summary": "- 本轮没有触发追逐场面。",
            "chase_tracker": "- 本轮没有追逐状态需要追踪。",
            "sanity_summary": "- 本轮没有触发理智检定或疯狂事件。",
        },
        "speaker_labels": {
            "keeper": "KP",
            "player": "玩家",
            "system": "system",
        },
        "outcome_labels": {
            "critical": "大成功",
            "extreme_success": "极难成功",
            "hard_success": "困难成功",
            "regular_success": "普通成功",
            "success": "成功",
            "failure": "失败",
            "fumble": "大失败",
        },
        "difficulty_labels": {
            "regular": "普通",
            "hard": "困难",
            "extreme": "极难",
            "opposed": "对抗",
            "combined": "联合",
            "sanity": "理智",
        },
        "raw_payload_fallback": False,
    },
    "en-US": {
        "language": "en-US",
        "display_name": "English",
        "output_instruction": "Use English for player-visible narration, table dialogue, recaps, and reports.",
        "name_policy": "Use customary English names and established scenario terminology.",
        "term_policy": "Use localized_terms.en-US for player-visible aliases when the source term needs an English table form.",
        "report_labels": BASE_REPORT_LABELS,
        "report_heading_labels": BASE_REPORT_HEADING_LABELS,
        "report_field_labels": BASE_REPORT_FIELD_LABELS,
        "empty_report_lines": BASE_EMPTY_REPORT_LINES,
        "speaker_labels": BASE_SPEAKER_LABELS,
        "outcome_labels": {},
        "difficulty_labels": {},
        "raw_payload_fallback": True,
    },
    "ja-JP": {
        "language": "ja-JP",
        "display_name": "Japanese",
        "output_instruction": "Use Japanese for player-visible narration, table dialogue, recaps, and reports.",
        "name_policy": "Foreign names should use customary Japanese katakana forms or established translated names.",
        "term_policy": "Use localized_terms.ja-JP for people, places, factions, handouts, scenario titles, and special terms.",
        "report_labels": {
            "roll_sentence": "- {skill}：{actor}は {roll} / {target} を振り、結果は{outcome}。",
            "difficulty": "難易度",
            "goal": "目的",
            "difficulty_rationale": "難易度の理由",
            "failure_consequence": "失敗時の結果",
            "pushed_roll": "プッシュロール",
            "push_justification": "プッシュ理由",
            "foreshadowed_failure": "失敗予告",
            "skill_check_earned": "成長チェック",
            "san_loss": "SAN 喪失",
            "yes": "yes",
            "no": "no",
        },
        "report_heading_labels": {
            "Battle Report": "プレイ報告",
            "Run Setup": "実行設定",
            "Module": "シナリオ",
            "Character Dossier": "キャラクター記録",
            "Investigator Chronicle": "探索者履歴",
            "Scene-by-Scene Replay": "シーン別リプレイ",
            "Actual Play Replay": "実プレイリプレイ",
            "Session Transcript": "セッション記録",
            "Major Player Decisions": "主なプレイヤー判断",
            "Rules & Rolls Recap": "ルールとロールの要約",
            "Mechanical Log": "メカニクス記録",
            "Important Rolls": "重要なロール",
            "State Changes": "状態変化",
            "Combat Summary": "戦闘要約",
            "Chase Summary": "チェイス要約",
            "Chase Tracker": "チェイス追跡",
            "Sanity Summary": "正気度要約",
            "Clues Found": "発見した手がかり",
            "Session Ending": "セッション終了",
            "Story Recap": "物語の要約",
            "Player Feedback On KP": "KP へのプレイヤーフィードバック",
            "Localization Appendix": "ローカライズ付録",
        },
        "report_field_labels": {
            "Run ID": "実行 ID",
            "Campaign": "キャンペーン",
            "Era": "時代",
            "Dice Mode": "ダイス方式",
            "Spoiler Policy": "ネタバレ方針",
            "Play Language": "プレイ言語",
            "Language Profile": "言語プロファイル",
            "Localized Terms": "ローカライズ用語",
            "Player Profile": "プレイヤープロファイル",
            "Scenario": "シナリオ",
            "Scenario ID": "シナリオ ID",
            "Source": "出典",
            "Opening Scene": "導入シーン",
        },
        "empty_report_lines": {
            "combat_summary": "- 今回は戦闘場面は発生していない。",
            "chase_summary": "- 今回はチェイス場面は発生していない。",
            "chase_tracker": "- 今回は追跡するチェイス状態はない。",
            "sanity_summary": "- 今回は正気度判定や狂気イベントは発生していない。",
        },
        "speaker_labels": {
            "keeper": "KP",
            "player": "プレイヤー",
            "system": "system",
        },
        "outcome_labels": {
            "critical": "クリティカル",
            "extreme_success": "イクストリーム成功",
            "hard_success": "ハード成功",
            "regular_success": "レギュラー成功",
            "success": "成功",
            "failure": "失敗",
            "fumble": "ファンブル",
        },
        "difficulty_labels": {
            "regular": "レギュラー",
            "hard": "ハード",
            "extreme": "イクストリーム",
            "opposed": "対抗",
            "combined": "複合",
            "sanity": "正気度",
        },
        "raw_payload_fallback": True,
    },
}


def language_profile(play_language: str | None = None) -> dict[str, Any]:
    language = play_language or DEFAULT_PLAY_LANGUAGE
    if language in LANGUAGE_PROFILES:
        return deepcopy(LANGUAGE_PROFILES[language])
    profile = deepcopy(LANGUAGE_PROFILES["en-US"])
    profile.update({
        "language": language,
        "display_name": language,
        "output_instruction": f"Use {language} for player-visible narration, table dialogue, recaps, and reports.",
        "name_policy": f"Use customary {language} forms for names and setting terms when available.",
        "term_policy": f"Use localized_terms.{language} for player-visible people, places, factions, handouts, scenario titles, and special terms.",
    })
    profile["empty_report_lines"] = BASE_EMPTY_REPORT_LINES
    profile["speaker_labels"] = BASE_SPEAKER_LABELS
    profile["report_heading_labels"] = BASE_REPORT_HEADING_LABELS
    profile["report_field_labels"] = BASE_REPORT_FIELD_LABELS
    return profile
